##########################################################
#                                                        #
# This package contains the components and UI elements I #
# use to configure the homeassistant web-based interface #
#                                                        #
##########################################################


homeassistant:
  customize_glob:
    "weblink.*":
      icon: mdi:web



http:
  api_password: !secret api_password
  ip_ban_enabled: True
  login_attempts_threshold: 3


config:


recorder:
  purge_interval: 7
  purge_keep_days: 14


logbook:      
  exclude:
    domains:
      - weblink
      - sensor
      - group


panel_iframe:
  kodi:
    title: 'Kodi'
    url: !secret iframe_kodi_url
    icon: mdi:kodi

  router:
    title: 'Router'
    url: !secret iframe_router_url
    icon: mdi:access-point-network


frontend:
  javascript_version: auto
  themes:
    midnight:
      primary-color: '#5294E2'
      accent-color: '#E45E65'
      dark-primary-color: 'var(--accent-color)'
      light-primary-color: 'var(--accent-color)'
      primary-text-color: '#FFFFFF'
      text-primary-color: 'var(--primary-text-color)'
      secondary-text-color: '#5294E2'
      disabled-text-color: '#7F848E'
      label-badge-border-color: 'green'
      primary-background-color: '#383C45'
      secondary-background-color: '#383C45'
      divider-color: 'rgba(0, 0, 0,,.12)'                                          
      table-row-background-color: '#353840'
      table-row-alternative-background-color: '#3E424B'
      paper-listbox-color: 'var(--primary-color)'
      paper-listbox-background-color: '#2E333A'
      paper-grey-50: 'var(--primary-text-color)'                                   
      paper-grey-200: '#414A59'
      paper-card-header-color: 'var(--accent-color)'
      paper-card-background-color: '#434954'
      paper-dialog-background-color: '#434954'
      paper-item-icon-color: 'var(--primary-text-color)'
      paper-item-icon-active-color: '#F9C536'
      paper-item-icon_-_color: 'green'           
      paper-item-selected_-_background-color: '#434954'
      paper-tabs-selection-bar-color: 'green'
      label-badge-red: 'var(--accent-color)'
      label-badge-text-color: 'var(--primary-text-color)'
      label-badge-background-color: '#2E333A'
      paper-toggle-button-checked-button-color: 'var(--accent-color)'
      paper-toggle-button-checked-bar-color: 'var(--accent-color)'
      paper-toggle-button-checked-ink-color: 'var(--accent-color)'
      paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
      paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'  
      paper-slider-knob-color: 'var(--accent-color)'
      paper-slider-knob-start-color: 'var(--accent-color)'
      paper-slider-pin-color: 'var(--accent-color)'
      paper-slider-active-color: 'var(--accent-color)'
      paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
      paper-slider-secondary-color: 'var(--secondary-background-color)'
      paper-slider-disabled-active-color: 'var(--disabled-text-color)'
      paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
      google-red-500: '#E45E65'
      google-green-500: '#39E949'

    darkcyan:
      primary-color: "#00bcd4"
      disabled-text-color: "#545454"
      divider-color: "rgba(255, 255, 255, 0.12)"
      paper-card-background-color: "#4e4e4e"
      paper-grey-200: "#191919"
      paper-item-icon-color: "#d3d3d3"
      paper-listbox-background-color: "#202020"
      paper-listbox-color: "#FFFFFF"      
      primary-background-color: "#303030"
      primary-text-color: "#cfcfcf"      
      secondary-background-color: "#2b2b2b"
      secondary-text-color: "#04a7bc"
      label-badge-background-color: "var(--secondary-background-color)"
      label-badge-text-color: "var(--text-primary-color)"
      paper-card-header-color: "#var(--paper-item-icon-color)"
      paper-grey-50: "var(--primary-text-color)"
      paper-item-icon-active-color: "var(--primary-color)"
      paper-item-icon_-_color: "var(--primary-text-color)"
      paper-slider-active-color: "var(--primary-color)"
      paper-slider-knob-color: "var(--primary-color)"
      paper-slider-knob-start-color: "var(--primary-color)"
      paper-slider-pin-color: "var(--primary-color)"
      paper-slider-secondary-color: "var(--light-primary-color)"     
      paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
      paper-toggle-button-checked-button-color: "var(--primary-color)"
      paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
      paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"

automation:
  - alias: Set UI theme
    initial_state: 'on' 
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: sensor.dark_outside
      - platform: time
        at: '23:00:00'
    action:
      - service_template: frontend.set_theme
        data_template:
          name: >-
            {% if (states.sensor.dark_outside.state == "true") %} midnight
            {% elif (now().hour == "23") %} darkcyan
            {% else %} default
            {% endif %}
