################################
#Sets the correct scene for the#
#landing light when auto-on    #
################################

landing_light_scene:
  sequence:
    - service: scene.turn_on
      entity_id: scene.landing_evening
    - condition: or
      conditions:
        - condition: time
          after: '21:30:00'
        - condition: time
          before: '07:30:00'
    - service: scene.turn_on
      entity_id: scene.landing_night