###################################
#Obtains environmental information#
#and presents it as sensor reading#
###################################

- platform: time_date
  display_options:
   - 'time'
   - 'date'