################################################################
#                                                              #
# This file defines the containers running in the docker stack #
#                                                              #
################################################################

version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    network_mode: host
    environment:
      - &user
        PUID=1000
      - &group
        PGID=1000
    volumes:
      - &localtime
        /etc/localtime:/etc/localtime:ro
      - /opt/docker/homeassistant:/config
    devices:
      - /dev/ttyS0:/dev/ttyS0:rwm
    restart: &restart
      on-failure
    depends_on:
      - "mosquitto"
      - "marytts"
      - "mariadb"

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    environment:
      - *user
      - *group
    volumes:
      - *localtime
      - /opt/docker/mosquitto:/mosquitto/config:ro
      - /opt/docker/mosquitto:/mosquitto/data
    restart: *restart

  marytts:
    container_name: marytts
    image: sliversniper/marytts
    ports:
      - "59125:59125"
    environment: 
      - *user
      - *group
    volumes:
      - *localtime
    restart: *restart

  mariadb:
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - *user
      - *group
      - MYSQL_DATABASE=homeassistant
      - MYSQL_USER=homeassistant
      - MYSQL_PASSWORD=homeassistant
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - *localtime
      - /opt/docker/mariadb:/var/lib/mysql
    restart: *restart

  portainer:
    container_name: portainer
    image: portainer/portainer
    ports:
      - "9000:9000"
    environment:
      - *user
      - *group
    volumes:
      - *localtime
      - /opt/docker/portainer:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock
    restart: *restart

  organizr:
    container_name: organizr
    image: lsiocommunity/organizr
    ports:
      - "80:80"
      - "443:443"
    environment:
      - *user
      - *group
    volumes:
      - *localtime
      - /opt/docker/organizr:/config:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: *restart

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing
    network_mode: host
    environment:
      - *user
      - *group
    volumes:
      - *localtime
      - /opt/docker/syncthing:/config
      - /opt:/config/Sync
    restart: unless-stopped
