#################################
#Placing entities on the card   #
#################################

masterbed_modes:
  name: Modes
  control: hidden
  entities:
  - script.lullaby
  - script.romance