#################################
#Placing entities on the card   #
#################################

Weblink:
  - weblink.home_assistant
  - weblink.ha_forums
  - weblink.github
  - weblink.travis_ci