################################################
#                                              #
# This package creates a device that allows me #
# to set a boolean to show the system in       #
# "Maintenance Mode", and manage backing up,   #
# upgrading and pulling config from Github     #
#                                              #
################################################


homeassistant:
  customize_glob:
    "weblink.*":
      icon: mdi:web


  customize:
    input_text.github_message:
      icon: mdi:pencil
    
    script.sync_dropbox:
      icon: mdi:dropbox

    script.upgrade_hass:
      icon: mdi:cloud-check

    script.github_push:
      icon: mdi:github-circle

    script.github_pull:
      icon: mdi:github-box
    
    sensor.mfsocialhomeassistant_last_build_id:
      friendly_name: "Last build ID"

    sensor.mfsocialhomeassistant_last_build_finished_at:
      friendly_name: "Last build time"

    sensor.mfsocialhomeassistant_last_build_state:
      friendly_name: "Status"

    sensor.mfsocialhomeassistant_state:
      hidden: true

    sensor.mfsocialhomeassistant_last_build_started_at:
      hidden: true

    sensor.mfsocialhomeassistant_last_build_duration:
      hidden: true

      
input_boolean:
  maintenance_mode:
    name: Maintenance mode
    icon: mdi:auto-fix


input_text:
  github_message:
    name: Commit Message
    initial: Push from local
    
    
weblink:
  entities:
    - name: Github
      url: https://github.com/mf-social/Home-Assistant
    - name: Travis CI
      url: https://travis-ci.org/
    - name: Configure Alexa
      url: https://alexa.amazon.co.uk/spa/index.html#smart-home
    - name: Dropbox
      url: https://dropbox.com
    - name: Router
      url: !secret weblink_router


script:
  upgrade_hass:
    alias: Upgrade HA and Restart
    sequence:
      - service: shell_command.upgrade_hass

  github_pull:
    alias: Pull from Github and Restart
    sequence:
      - service: shell_command.github_pull

  github_push:
    alias: Push to Github
    sequence:
      #- service: shell_command.github_push {{states.input_text.github_message.state}}

  sync_dropbox:
    alias: Sync Dropbox
    sequence:
      - service: shell_command.sync_dropbox

  quick_restart:
    alias: Restart Homeassistant
    sequence:
      - service: shell_command.quick_restart

  quick_reboot:
    alias: Reboot Node-zero
    sequence:
      - service: shell_command.quick_reboot


shell_command:
  upgrade_hass: /home/hass/.homeassistant/extras/bash_scripts/upgrade-hass.sh

  sync_dropbox: /home/hass/.homeassistant/extras/bash_scripts/sync-dropbox.sh

  github_pull: /home/hass/.homeassistant/extras/bash_scripts/pull-from-github.sh

  quick_restart: sudo systemctl restart home-assistant.service

  quick_reboot: sudo reboot

  #github_push: /home/hass/.homeassistant/extras/bash_scripts/send-to-github.sh {{github_message}}


sensor:
  - platform: travisci
    api_key: !secret sensor_travisci
    
    
group:
  Maintenance:
    control: hidden
    entities:
      - input_boolean.maintenance_mode
      - script.quick_restart
      - script.quick_reboot
      - script.upgrade_hass
      - script.github_pull
      - input_text.github_message
      - script.github_push
      - weblink.github
      - script.sync_dropbox
      - weblink.dropbox

  Configure external:
      - weblink.configure_alexa
      - weblink.router

  Travis CI:
    - weblink.travis_ci
    - sensor.mfsocialhomeassistant_last_build_state
    - sensor.mfsocialhomeassistant_last_build_id
    - sensor.mfsocialhomeassistant_last_build_finished_at


alert:
  maintenance_mode_alert:
    name: Maintenance Mode has been on for a long time
    done_message: Maintenance Mode de-activated
    entity_id: input_boolean.maintenance_mode
    repeat:
      - 60
    skip_first: true
    notifiers:
      - telegram_marc