#####################################################
#                                                   #
# This package creates a device with 2 UI elements  #
# that monitor whether there is anybody at home,    #
# and provides modes that assist with automations.  #
#                                                   #
# It also includes a guest mode option for people   #
# that may be in the house, but aren't tracked.     #
#                                                   #
#####################################################


homeassistant:
  customize_glob:
    "automation.*":
      confirm_controls_show_lock: true

  customize:
    group.all_automations:
      hidden: false
      hide_control: true
      confirm_controls_show_lock: true
      extra_badge:
        entity_id: group.all_automations

    group.phone_trackers:
      state_card_mode: badges

    sensor.home_status:
      icon: mdi:home-map-marker

    input_boolean.away_mode:
      hide_control: true
      extra_badge:
        entity_id: input_boolean.away_mode

    input_boolean.holiday_mode:
      hide_control: true
      extra_badge:
        entity_id: input_boolean.holiday_mode


device_tracker:
  platform: bluetooth_tracker
  new_device_defaults:
    track_new_devices: false


input_boolean:
  guest_mode:
    name: Guest mode
    icon: mdi:human-handsup

  holiday_mode:
    name: Holiday mode
    icon: mdi:airplane

  school_day_mode:
    name: School Day mode
    icon: mdi:school

  bathtime_mode:
    name: Bathtime mode
    icon: mdi:hot-tub

  cycling_mode:
    name: Cycling to work mode
    icon: mdi:bike

  away_mode:
    name: Away mode
    icon: mdi:alert-circle-outline

  kids_night_mode:
    name: Kids night monitor
    icon: mdi:human-child

  bedtime_mode:
    name: Bedtime mode
    icon: mdi:sleep


sensor:
  - platform: template
    sensors:
      home_status:
        friendly_name: 'Home status'
        value_template: >-
          {% if (states.group.phone_trackers.state == 'home') or (states.input_boolean.guest_mode.state == 'on') %}Occupied
          {% else %} Unoccupied
          {% endif %}


group:
  Phone trackers:
    - device_tracker.forthygpixel
    - device_tracker.lauras_iphone
    - device_tracker.iphone

  Adults:
    - device_tracker.forthygpixel
    - device_tracker.lauras_iphone
  
  occupancy_modes:
    name: Occupancy
    control: hidden
    entities:
      - group.phone_trackers
      - alarm_control_panel.alarm
      - sensor.home_status
      - input_boolean.guest_mode
      - input_boolean.away_mode
      - input_boolean.holiday_mode

  home_modes:
    name: Home Modes
    control: hidden
    entities:
      - group.all_automations
      - input_boolean.bathtime_mode
      - input_boolean.kids_night_mode
      - input_boolean.bedtime_mode
      - input_boolean.school_day_mode
      - input_boolean.cycling_mode
    
    
alert:
  guest_mode_alert:
    name: Guest Mode has been on for a long time
    done_message: Guest Mode de-activated
    entity_id: input_boolean.guest_mode
    repeat:
      - 240
      - 120
    skip_first: true
    notifiers:
      - mf


automation:
  - alias: 'Reset occupancy booleans'
    trigger:
      platform: state
      entity_id: group.phone_trackers
      to: 'home'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.guest_mode
      - service: input_boolean.turn_off
        entity_id: input_boolean.away_mode
      - service: input_boolean.turn_off
        entity_id: input_boolean.holiday_mode

  - alias: 'Reset occupancy booleans - guest'
    trigger:
      platform: state
      entity_id: input_boolean.guest_mode
      to: 'on'
    condition:
      condition: state
      entity_id: sensor.home_status
      state: 'Unoccupied' 
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.away_mode
    
  - alias: 'Nobody home'
    trigger:
      platform: state
      entity_id: sensor.home_status
      to: 'Unoccupied'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.play_radio
      - service: switch.turn_off
        entity_id: switch.google_music
      - service: homeassistant.turn_off
        entity_id: group.all_lights
      - service: media_player.turn_off
        entity_id: media_player.living_room_kodi
      - service: homeassistant.turn_on
        entity_id: input_boolean.away_mode
    
  - alias: 'Set Holiday Mode'
    trigger:
      platform: state
      entity_id: input_boolean.away_mode
      to: 'on'
      for:
        hours: 24
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.holiday_mode
      - service: input_boolean.turn_off
        entity_id: input_boolean.away_mode

  - alias: 'New trackable device detected'
    trigger:
      platform: event
      event_type: device_tracker_new_device
    action:
      service: notify.mf
      data:
        message: 'New trackable device detected'
