###################################################
#                                                 #
# This package creates a quick timer device that  #
# allows me to drag a slider to select the time   #
# and then notifies me when the timer has expired #
#                                                 #
###################################################


input_number:
  timer_minutes:
    name: Minutes
    icon: mdi:timer
    initial: 0
    min: 0
    max: 60
    step: 1


timer:
  quick_timer:
    name: Quick Timer
    icon: mdi:clock-end


group:
  quick_timer:
    name: 'Timer'
    entities:
      - input_number.timer_minutes
      - timer.quick_timer


automation:
  - alias: 'timer set'
    trigger:
      platform: state
      entity_id: input_number.timer_minutes
    action:
      - service: timer.start
        entity_id: timer.quick_timer
        data_template:
          duration: '00:{{states.input_number.timer_minutes.state|int}}:00'
      - condition: template
        value_template: '{{ states.input_number.timer_minutes.state|float == 0}}'
      - service: timer.cancel
        entity_id: timer.quick_timer
      
  - alias: 'timer expired'
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.quick_timer
    action:
      - service: notify.mf
        data:
          message: "The timer has expired - Home Assistant"
      - service: tts.google_say
        entity_id: media_player.everywhere
        data:
          message: 'The timer has expired, The timer has expired'