###################################
#Links to websites presented in UX#
###################################

entities:
  - name: Home Assistant
    url: https://home-assistant.io
  - name: HA Forums
    url: https://community.home-assistant.io/
  - name: Github
    url: https://github.com/mf-social/Home-Assistant
  - name: Travis CI
    url: https://travis-ci.org/