################################
#A one-touch scene controller  #
################################

name: Landing_night
entities:
  light.landing:
    state: on
    transition: 4
    brightness: 85
    rgb_color: [254,63,189]