################################
#A one-touch scene controller  #
################################

name: Landing_evening
entities:
  light.landing:
    state: on
    transition: 4
    brightness: 180
    rgb_color: [255,206,119]