########################################
#Notify if critical device goes offline#
########################################

alias: Alert when a critical device goes offline
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.broadlink
    to: 'off'
    for:
      minutes: 2
  - platform: state
    entity_id: binary_sensor.hue_hub
    to: 'off'
    for:
      minutes: 2
  - platform: state
    entity_id: binary_sensor.tp_link
    to: 'off'
    for:
      minutes: 2  
  - platform: state
    entity_id: binary_sensor.cctv
    to: 'off'
    for:
      minutes: 2
  - platform: state
    entity_id: binary_sensor.amazon_echo
    to: 'off'
    for:
      minutes: 2
action:
  service: notify.telegram_marc
  data_template:
    message: '{{trigger.to_state.attributes.friendly_name}} has gone offline.'
