################################
#Settings for the iframe panels#
################################

kodi:
  title: 'Kodi'
  url: !secret iframe_kodi_url
  icon: mdi:kodi

router:
  title: 'Router'
  url: !secret iframe_router_url
  icon: mdi:access-point-network