############################################
#                                          #
# This package manages the lighting scenes #
#                                          #
############################################


input_select:
  bedroom_scenes:
    name: Scenes
    options:
      - Select
      - Arctic aurora
      - Bright
      - Concentrate
      - Dimmed
      - Energize
      - Nightlight
      - Read
      - Relax
      - Savanna sunset
      - Spring blossom
      - Tropical twilight
    initial: Select
    icon: mdi:creation


scene:
  - name: Livingroom dim
    entities:
      light.livingroom:
        state: on
        transition: 4
        brightness: 125

  - name: Livingroom movie
    entities:
      light.livingroom:
        state: on
        transition: 4
        brightness: 35

  - name: Livingroom bright
    entities:
      light.livingroom:
        state: on
        transition: 4
        brightness: 255

  - name: Livingroom sunset
    entities:
      light.livingroom:
        state: on
        transition: 600
        brightness: 255

  - name: Boys bright
    entities:
      light.boys:
        state: on
        transition: 4
        brightness: 200

  - name: Boys dim
    entities:
      light.boys:
        state: on
        transition: 4
        brightness: 125

  - name: Boys night
    entities:
      light.boys:
        state: on
        transition: 4
        brightness: 5

  - name: Girls bright
    entities:
      light.girls:
        state: on
        transition: 4
        brightness: 200

  - name: Girls dim
    entities:
      light.girls:
        state: on
        transition: 4
        brightness: 125

  - name: Girls night
    entities:
      light.girls:
        state: on
        transition: 4
        brightness: 5


automation:
  - alias: Lighting - Reset scene selector (Bedroom)
    initial_state: on
    trigger:
      platform: state
      entity_id: light.bedroom
      to: 'off'
    condition:
      condition: template
      value_template: "{{ not is_state('input_select.bedroom_scenes' , 'Select') }}"
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.bedroom_scenes
        option: Select

  - alias: Lighting - Trigger scene (Bedroom)
    initial_state: on
    trigger:
      platform: state
      entity_id: input_select.bedroom_scenes
    condition:
      condition: template
      value_template: "{{ not is_state('input_select.bedroom_scenes' , 'Select') }}"
    action:
      service: script.set_hue_scene
      data_template:
        group: "Bedroom"
        scene: "{{ states('input_select.bedroom_scenes') }}"


script:
  set_hue_scene:
    sequence:
      - service: hue.hue_activate_scene
        data_template:
          group_name: "{{ group }}"
          scene_name: "{{ scene }}"
