######################################
#Switches on the xmas lights when the#
#living room lights are switched on  #
######################################

alias: "Xmas lights"
initial_state: on
trigger:
  platform: state
  entity_id: light.living_room
  to: 'on'
action:
  service: homeassistant.turn_on
  entity_id: switch.xmas_lights