#############################################
#Xmas lights off when there's a press-hold  #
#on the off switch for the living room light#
#############################################

alias: xmas lights off
initial_state: 'on'
trigger:
  platform: state
  entity_id: light.living_room
  to: 'off'
action:
  service: homeassistant.turn_off
  entity_id: switch.xmas_lights