################################
#A one-touch scene controller  #
################################

master_bedroom_concentrate:
  sequence:
    - service: hue.hue_activate_scene
      data:
        group_name: "Master Bedroom"
        scene_name: "Concentrate"