############################################
#                                          #
# This package contains the components,    #
# sensors and UI elements for the hardware #
# I have connected to my homeassistant     #
#                                          #
############################################


homeassistant:
  customize:
    light.master_bedroom:
      hidden: true

    light.living_room:
      hidden: true

    light.landing_g:
      hidden: true

    light.bathroom_g:
      hidden: true
    
    sensor.master_bedroom_switch:
      icon: mdi:remote

  customize_glob:
    "sensor.*zwave*":
      hidden: true

    "light.*zwave*_2*":
      hidden: true

    "zwave.*":
      icon: mdi:signal-variant


#zwave:
#  usb_path: /dev/ttyAMA0


hue:
  bridges:
    - host: !secret hue_light_host
    
    
media_player:
  - platform: cast

  - platform: kodi
    name: Living Room Kodi
    host: !secret media_host
    port: !secret media_port
    enable_websocket: false
    username: !secret media_username
    password: !secret media_password
    turn_off_action:
      service: media_player.kodi_call_method
      data_template:
        entity_id: '{{ entity_id }}'
        method: System.Shutdown
        
    
switch: 
  - platform: tplink
    host: !secret switch_tplink_host

  - platform: broadlink
    host: !secret switch_broadlink_host
    mac: !secret switch_broadlink_mac
    friendly_name: 'IR remote'
    switches:
      tv_lg_on_off:
        friendly_name: 'TV power'
        command_on: 'JgAAAQABJ5QVEBISFTQUERUQExITERUQFTQVNBUREjcSNxM2FDUTNhMRFREUNRITEhIUERQ1FTQVNBU0FBETNxI3FDUTERUQFQAFJAABKUgTAAxOAAEoRxMADE4AASdJFQAMTAABJ0gVAAxNAAEoSBMADE4AAShHFQAMTAABJ0kTAAxOAAEoRxUADE0AAShHFAAMTQABKUcVAAxMAAEoRxUADE0AAShHFQAMTQABKEcUAAxNAAEoSBQADE0AAShHFQAMTQABKEgSAAxOAAEpRxQADE0AAShIFAAMTAABKUcVAAxNAAEoRxQADE0AAShIFAAMTQABKEcUAAxNAAEnSRQADQUAAAAAAAAAAA=='
        command_off: 'JgCAAAABKZITERUQFTQVEBMSExEVEBUQEzYUNhMRFDUVNBU0FTQVNRQ1FBEUNRUQExEVEBU0FTQVEBM2FBEUNRQ1FTQVEBUQEwAFJwABJ0gVAAxNAAEnSBQADE0AAShIEwAMTgABKEcVAAxMAAEpRxUADE0AAShHEwAMTgABKEgUAA0FAAAAAAAAAAA='
      tv_lg_hdmi_1:
        friendly_name: 'TV Hdmi 1'
        command_on: 'ZNyOPZtPBS3RwnscCDbyCxUQExITERUQFTQVNA=='


sensor:
  - platform: hue_sensor


binary_sensor:
  - platform: ping
    host: !secret hue_light_host
    name: Hue Hub

  - platform: ping
    host: !secret switch_tplink_host
    name: TP Link

  - platform: ping
    host: !secret switch_broadlink_host
    name: Broadlink

  - platform: ping
    host: !secret cctv_host
    name: CCTV


input_select:
  living_room_scenes:
    name: Scenes
    options:
      - Select
      - Dim
      - Bright
    initial: Select
    icon: mdi:creation

  master_bedroom_scenes:
    name: Scenes
    options:
      - Select
      - Arctic Aurora
      - Bright
      - Concentrate
      - Dimmed
      - Energize
      - Nightlight
      - Read
      - Relax
      - Savanna Sunset
      - Spring Blossom
      - Tropical Twilight
    initial: Select
    icon: mdi:creation


group:
#  Zwave:
#    - zwave.boys_room_zwave_dimmer
#    - zwave.living_room_zwave_dimmer
#    - zwave.zwaveme_razberry_controller_2016_zwave

  master_bedroom_lights:
    name: Lights
    entities:
      - light.mb_ceiling
      - light.mb_stairs
      - input_select.master_bedroom_scenes

  livingroom_lights:
    name: Lights
    entities:
      - light.lr_left
      - light.lr_right
      - input_select.living_room_scenes

  other_lights:
    name: Lights
    control: hidden
    entities:
      - light.landing
      - light.bathroom


  xmas_switch:
    name: Xmas lights
    control: hidden
    entities:
      - switch.xmas_lights

  Hue:
    - sensor.master_bedroom_switch
    - sensor.living_room_switch
    - sensor.bathroom_motion_motion

  Devices:
    - binary_sensor.broadlink
    - binary_sensor.hue_hub
    - binary_sensor.tp_link
    - binary_sensor.cctv