###########################################################
#                                                         #
# This package contains the components and sensors I use  #
# to monitor the Homeassistant software and system itself #
# and the UI elements I use to display the information    #
#                                                         #
###########################################################


homeassistant:
  customize:
    sensor.ha_upstream:
      friendly_name: "Upstream HA version"
      icon: mdi:cloud-sync

    sensor.installed_ha_version:
      icon: mdi:home-outline


updater:
  include_used_components: true


sensor:
  - platform: cpuspeed

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      - type: since_last_boot
      
  - platform: version
    name: Installed HA version

  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: HA upstream
    value_template: '{{ value_json.info.version }}'
    scan_interval: 3600


group:
  System:
    - updater.updater
    - sensor.installed_ha_version
    - sensor.ha_upstream
    - sensor.cpu_speed
    - sensor.cpu_used
    - sensor.disk_used_
    - sensor.last_boot
    - sensor.ram_used
    - sensor.since_last_boot