##############################
#Notifies me if there are any#
#failed logins to HA         #
##############################

alias: 'Send notification upon failed login attempt'
initial_state: 'on'
trigger:
  platform: state
  entity_id: persistent_notification.httplogin
condition:
  condition: template
  value_template: "{{ trigger.to_state.state != off }}"
action:
  service: notify.telegram_marc
  data_template:
    message: "{{ trigger.to_state.state }}"