########################################
#Power cut notification - if the system#
#restarts and the maintenance_mode    #
#boolean is off, send an alert         #
########################################

alias: 'Power cut notification'
initial_state: 'on'
trigger:
  platform: homeassistant
  event: start
condition:
  condition: state
  entity_id: input_boolean.maintenance_mode
  state: 'off'
action:
  service: notify.telegram_marc
  data_template:
    message: "Home Assistant has restarted and is not in Maintenance Mode.  Power cut?"
    data:
      keyboard:
        - '/status'
        - '/maintenance'