#############################
#Sets the daytime UI theme  #
#############################

alias: 'Day UI theme'
initial_state: 'on'
trigger:
  platform: sun
  event: sunrise
action:
  service: frontend.set_theme
  data:
    name: default