#############################
#Sets the night UI theme    #
#############################

alias: 'Night UI theme'
initial_state: 'on'
trigger:
  platform: time
  at: '23:00:00'
action:
  service: frontend.set_theme
  data:
    name: darkcyan