###########################################
#This automation switches on the living   #
#room lights when instructed via telegram #
###########################################

alias: 'Telegram set livingroom lights on'
initial_state: 'on'
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/LivingRoom'
action:
  - service: homeassistant.toggle
    entity_id: light.living_room
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: 'Livingroom lights have been turned {{states.light.living_room.state}}.'