####################################
#This automation switches away mode#
#on when instructed via telegram   #
####################################

alias: 'Telegram set away mode'
initial_state: 'on'
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/away'
action:
  - service: input_boolean.toggle
    entity_id: input_boolean.away_mode
  - service: telegram_bot.send_message
    data_template:
      target: '{{ trigger.event.data.user_id }}'
      message: 'Away mode has been turned {{states.input_boolean.away_mode.state}}'