################################
#Runs a bash script that pulls #
#the config from github        #
################################

github_pull:
  alias: Pull from Github and Restart
  sequence:
    - service: shell_command.github_pull
