##########################################
#Runs a bash script that stops the HA    #
#service, runs apt-get upgrade on the    #
#device, then runs HA upgrade and reboots#
##########################################

