########################################################
#                                                      #
# This package contains automations that respond to    #
# voice commands by actioning the request              #
#                                                      #
########################################################


homeassistant:
  customize:
    switch.movie_mode:
      icon: mdi:movie-outline

emulated_hue:
  host_ip: !secret host_ip
  expose_by_default: false
  entities:
    switch.heater:
      name: "Bedroom heater"
      hidden: false

    switch.xmas_lights:
      name: "Christmas Lights"
      hidden: false

    switch.bathtime_mode:
      name: "Bathtime Mode"
      hidden: false

    input_boolean.movie_mode:
      name: "Movie Mode"
      hidden: false

    light.floor_lights:
      name: "Floor lights"
      hidden: false


input_boolean:
  movie_mode:


switch:
  platform: template
  switches:
    movie_mode:
      value_template: "{{ is_state('input_boolean.movie_mode' , 'on') }}"
      turn_on:
        service: homeassistant.turn_on
        entity_id: input_boolean.movie_mode
      turn_off:
        service: homeassistant.turn_off
        entity_id: input_boolean.movie_mode

automation:
  alias: Interactive - Movie mode
  trigger:
    platform: state
    entity_id: input_boolean.movie_mode
  action:
    service_template: "script.movie_mode_{{ states('input_boolean.movie_mode')  }}"
