########################################################
#                                                      #
# This package contains automations that respond to    #
# voice commands by actioning the request              #
#                                                      #
########################################################


homeassistant:
  customize:
    switch.movie_mode:
      icon: mdi:movie-outline

emulated_hue:
  host_ip: !secret host_ip
  expose_by_default: false
  entities:
    switch.heater:
      name: "Bedroom heater"
      hidden: false

    switch.xmas_lights:
      name: "Christmas Lights"
      hidden: false

    switch.bathtime_mode:
      name: "Bathtime Mode"
      hidden: false

    switch.movie_mode:
      name: "Movie Mode"
      hidden: false

    light.floor_lights:
      name: "Floor lights"
      hidden: false


switch:
  platform: template
  switches:
    movie_mode:
      value_template: "{{ is_state('switch.kitchen_motion_status' , 'off') }}"
      turn_on:
        service: script.movie_mode_on
      turn_off:
        service: script.movie_mode_off
