#########################################################
#                                                       #
# This package contains automations that send reminders #
#                                                       #
# DEPENDS ON: Occupancy                                 #
#                                                       #
#########################################################


automation:
  - alias: Reminder - Bin day
    initial_state: on
    trigger:
      platform: time
      at: '18:15:00'
    condition:
      - condition: time
        weekday:
          - wed
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'off'
    action:
      - wait_template: "{{ is_state('group.adults' , 'home') }}"
        timeout: 14:00:00
      - delay: 00:15:00
      - service: script.notify
        data:
          tell: adults
          message: "The bins need to go out tonight."

  - alias: Reminder - Refresh date countdown sensors
    initial_state: on
    trigger:
      - platform: time
        at: '00:00:01'
      - platform: homeassistant
        event: start
    action:
      - service: python_script.date_countdown
        data:
          name: !secret name_mf
          type: birthday
          date: !secret birthday_mf
      - service: python_script.date_countdown
        data:
          name: !secret name_ls
          type: birthday
          date: !secret birthday_ls
      - service: python_script.date_countdown
        data:
          name: !secret name_cg
          type: birthday
          date: !secret birthday_cg
      - service: python_script.date_countdown
        data:
          name: !secret name_df
          type: birthday
          date: !secret birthday_df
      - service: python_script.date_countdown
        data:
          name: !secret name_cf
          type: birthday
          date: !secret birthday_cf
      - service: python_script.date_countdown
        data:
          name: !secret name_vf
          type: birthday
          date: !secret birthday_vf
      - service: python_script.date_countdown
        data:
          name: !secret name_zs
          type: birthday
          date: !secret birthday_zs
      - service: python_script.date_countdown
        data:
          name: !secret anniversary
          type: anniversary
          date: !secret date_anniversary

  - alias: Reminder - 7 days to significant date
    initial_state: on
    trigger:
      - platform: state
        entity_id: 
          - !secret mf_birthday_sensor
          - !secret ls_birthday_sensor
          - !secret cg_birthday_sensor
          - !secret df_birthday_sensor
          - !secret cf_birthday_sensor
          - !secret vf_birthday_sensor
          - !secret zs_birthday_sensor
          - !secret anniversary_sensor
        to: '7'
    action:
      - wait_template: "{{ states('sensor.time') == '10:00' }}"
      - service: script.notify
        data_template:
          tell: adults
          message: "{{ trigger.to_state.attributes.friendly_name }} is in {{ trigger.to_state.attributes.days }}"
