###########################################################
#                                                         #
# This package contains the components I use to configure #
# and access the homeassistant web-based interface        #
#                                                         #
###########################################################


http:
  ip_ban_enabled: True
  login_attempts_threshold: 3
  base_url: !secret base_url


frontend:
  javascript_version: auto
  themes: !include_dir_merge_named ../../includes/themes/


config:


map:


automation:
  - alias: Interface - Set UI theme
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id:
          - alarm_control_panel.alarm
          - input_boolean.maintenance_mode
          - input_boolean.dark
      - platform: time
        at: '23:00:00'
      - platform: time
        at: '07:00:00'
    action:
      service: frontend.set_theme
      data_template:
        name: >
          {% if not is_state ('alarm_control_panel.alarm' , 'disarmed') %} darkred
          {% elif is_state ('input_boolean.maintenance_mode' , 'on') %} darkorange
          {% elif ((now().hour == 23) or (now().hour < 7)) %} darkcyan
          {% elif is_state('input_boolean.dark' , 'on') %} midnight
          {% else %} default {% endif %}
