#######################################
#This automation replies to a telegram#
#message with home and away status    #
#######################################

alias: 'Telegram reply with People'
initial_state: 'on'
trigger:
  platform: event
  event_type: telegram_command
  event_data:
    command: '/people'
action:
  service: telegram_bot.send_message
  data_template:
    target: '{{ trigger.event.data.user_id }}'
    message: 'Currently home is {{states.sensor.home_status.state}}.
      
    Marc is at {{states.device_tracker.forthygpixel.state}}.
      
    Laura is at {{states.device_tracker.lauras_iphone.state}}.
      
    Courtney is at {{states.device_tracker.iphone.state}}.
      
    Guest mode is {{states.input_boolean.guest_mode.state}}.'
    keyboard: ["/away, /holiday" , "/guest, /lights", "/menu"]