##################################
#Notifies me if the havibeenpwned#
#sensor activates for any of my  #
#email addresses if breached     #
##################################

alias: 'Breach email haveibeenpwned daniel'
initial_state: 'on'
trigger:
  platform: numeric_state
  entity_id: !secret sensor_email_daniel
  above: 0
action:
  service: notify.telegram_marc
  data:
    message: 'Warning - HaveIbeenPwned detected a breach on Daniel email address'