#########################################################
#                                                       #
# This package creates a device which provides a music  #
# player of sorts in the front end, allowing to select  #
# from my google music playlists, and play them across  #
# the chromecasts, basically like a sonos system        #
#                                                       #
#########################################################


homeassistant:
  customize:
    switch.google_music:
      friendly_name: Play
      icon: mdi:play


input_select:
  google_music:
    name: Music
    options:
     - " "
    icon: mdi:music

  google_media_player:
    name: Media player
    options:
     - "kitchencca"
     - "bad"
     - "hele_huset"
     - "stue_kjokken"
    icon: mdi:speaker-wireless


input_number:
  volume_google_music:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05
    initial: '0.2'
    
    
switch:
 - platform: gmusic
   user: !secret google_music_user
   password: !secret google_music_pass
   device_id: !secret google_music_device_id
   media_player: google_media_player
   playlist: google_music


group:
  google_music:
    name: Google Music 
    entities:
    - switch.google_music
    - input_select.google_music
    - input_select.google_media_player
    - input_number.volume_google_music

automation:
  - alias: "Stop google music"
    initial_state: on
    trigger:
      platform: state
      entity_id: switch.google_music
      to: 'off'
    action:
      - service: media_player.turn_off
        data:
          entity_id:
            - media_player.kitchencca
            - media_player.livingroomcca
            - media_player.bedroomcca
            - media_player.downstairs_group
            - media_player.everywhere_group
      - service: input_number.set_value
        data_template:
          entity_id: input_number.volume_google_music
          value: 0.20

  - alias: 'Set Google Music Volume'
    initial_state: on
    trigger:
      platform: state
      entity_id: input_number.volume_google_music
    action:
      service: media_player.volume_set
      data_template:
        entity_id: >
          {% if is_state("input_select.google_media_player", "kitchencca") %} media_player.kitchencca
          {% endif %}
        volume_level: '{{  states.input_number.volume_radio.state  }}'