#################################
#Placing cards/entites on a tab #
#################################

downstairs:
  view: yes
  name: Downstairs
  icon: mdi:sofa
  entities:
    - group.livingroom_lights
    - group.xmas_switch
    - group.downstairs_alarm_clock
    - media_player.living_room_kodi
    - media_player.livingroomcca
    - media_player.kitchencca
    - media_player.downstairs_group