#################################
#Placing cards/entites on a tab #
#################################

media:
  view: yes
  name: Media
  icon: mdi:speaker-wireless
  entities:
    - media_player.living_room_kodi
    - media_player.kitchencca
    - media_player.bedroomcca
    - media_player.livingroomcca  
    - media_player.everywhere_group
    - media_player.downstairs_group
    - group.chromecast_radio