#################################
#Placing cards/entites on a tab #
#################################

settings:
  view: yes
  name: Settings
  icon: mdi:settings
  entities:
    - group.all_automations
    - group.all_scripts