############################################################
#                                                          #
# This package manages manual lighting changes from the UI #
#                                                          #
############################################################


input_select:
  master_bedroom_scenes:
    name: Scenes
    options:
      - Select
      - Arctic aurora
      - Bright
      - Concentrate
      - Dimmed
      - Energize
      - Nightlight
      - Read
      - Relax
      - Savanna sunset
      - Spring blossom
      - Tropical twilight
    initial: Select
    icon: mdi:creation


automation:
  - alias: reset_scene_selector master_bedroom
    trigger:
      platform: state
      entity_id: light.master_bedroom
      to: 'off'
    condition:
      condition: template
      value_template: "{{ not is_state('input_select.master_bedroom_scenes' ,'Select') }}"
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.master_bedroom_scenes
        option: Select

  - alias: trigger_scene_master_bedroom
    trigger:
      platform: state
      entity_id: input_select.master_bedroom_scenes
    condition:
      condition: template
      value_template: "{{ not is_state('input_select.master_bedroom_scenes' ,'Select') }}"
    action:
      service: script.set_hue_scene
      data_template:
        group: "Master Bedroom"
        scene: '{{ states.input_select.master_bedroom_scenes.state }}'