############################################################
#                                                          #
# This package manages manual lighting changes from the UI #
#                                                          #
############################################################


automation:
  - alias: reset_scene_selector master_bedroom
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: light.master_bedroom
      to: 'off'
    condition:
      condition: template
      value_template: "{{ not is_state('input_select.master_bedroom_scenes' ,'Select') }}"
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.master_bedroom_scenes
        option: Select

  - alias: reset_scene_selector living_room
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: light.living_room
      to: 'off'
    condition:
      condition: template
      value_template: "{{ not is_state('input_select.master_bedroom_scenes' ,'Select') }}"
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.living_room_scenes
        option: Select

  - alias: trigger_scene_master_bedroom
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_select.master_bedroom_scenes
    condition:
      condition: template
      value_template: "{{ not is_state('input_select.master_bedroom_scenes' ,'Select') }}"
    action:
      service_template: >-
         {% if is_state ('input_select.master_bedroom_scenes' ,'Spring Blossom') %} script.master_bedroom_spring_blossom
         {% elif is_state ('input_select.master_bedroom_scenes' , 'Savanna Sunset') %} script.master_bedroom_savanna_sunset
         {% elif is_state ('input_select.master_bedroom_scenes' , 'Relax') %} script.master_bedroom_relax
         {% elif is_state ('input_select.master_bedroom_scenes' , 'Reading') %} script.master_bedroom_read
         {% elif is_state ('input_select.master_bedroom_scenes' , 'Nightlight') %} script.master_bedroom_nightlight
         {% elif is_state ('input_select.master_bedroom_scenes' , 'Energize') %} script.master_bedroom_spring_energize
         {% elif is_state ('input_select.master_bedroom_scenes' , 'Dimmed') %} script.master_bedroom_dimmed
         {% elif is_state ('input_select.master_bedroom_scenes' , 'Concentrate') %} script.master_bedroom_concentrate
         {% elif is_state ('input_select.master_bedroom_scenes' , 'Bright') %} script.master_bedroom_bright
         {% elif is_state ('input_select.master_bedroom_scenes' , 'Arctic Aurora') %} script.master_bedroom_arctic_aurora
         {% elif is_state ('input_select.master_bedroom_scenes' , 'Tropical Twilight') %} script.master_bedroom_tropical_twilight
         {% endif %}

  - alias: trigger_scene_living_room
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: input_select.living_room_scenes
    condition:
      condition: template
      value_template: "{{ not is_state('input_select.living_room_scenes' ,'Select') }}"
    action:
      service: scene.turn_on
      data_template:
        entity_id: >-
         {% if is_state ('input_select.living_room_scenes' ,'Bright') %} scene.livingroom_bright
         {% elif is_state ('input_select.living_room_scenes' , 'Dim') %} scene.livingroom_dim
         {% endif %}
