############################################
#                                          #
# This package manages the lighting scenes #
#                                          #
############################################


homeassistant:
  customize_glob:
    "scene.*":
      icon: mdi:creation


scene:
  - name: Landing_evening
    entities:
      light.landing:
        state: on
        transition: 4
        brightness: 180
        rgb_color: [255,206,119]

  - name: Landing_night
    entities:
      light.landing:
        state: on
        transition: 4
        brightness: 85
        rgb_color: [254,63,189]

  - name: Livingroom dim
    entities:
      light.living_room:
        state: on
        transition: 4
        brightness: 125

  - name: Livingroom movie
    entities:
      light.living_room:
        state: on
        transition: 4
        brightness: 35

  - name: Livingroom bright
    entities:
      light.living_room:
        state: on
        transition: 3
        brightness: 255

  - name: Livingroom sunset
    entities:
      light.living_room:
        state: on
        transition: 600
        brightness: 255

  - name: Master bedroom wake up
    entities:
      light.master_bedroom:
        state: on
        transition: 120
        brightness: 180
        rgb_color: [255,160,39]


script:
  set_hue_scene:
    sequence:
      - service: hue.hue_activate_scene
        data_template:
          group_name: '{{ group }}'
          scene_name: '{{ scene }}'