
mqtt:
  broker: !secret mqtt_broker
  
  
emulated_hue:
  host_ip: !secret hue_host_ip
  listen_port: !secret hue_listen_port
  exposed_domains:
    - light
    - input_boolean
    - switch


sensor:
  - platform: mqtt
    name: "Doorbell"
    state_topic: "home-assistant/doorbell"
