

input_boolean:
  maintenance_mode:
    name: Maintenance mode
    icon: mdi:auto-fix


input_text:
  github_message:
    name: Commit Message
    initial: Push from local


script:
  upgrade_hass:
    alias: Upgrade HA and Restart
    sequence:
      - service: shell_command.upgrade_hass

  github_pull:
    alias: Pull from Github and Restart
    sequence:
      - service: shell_command.github_pull

  github_push:
    alias: Push to Github
    sequence:

  sync_dropbox:
    alias: Sync Dropbox
    sequence:
      - service: shell_command.sync_dropbox


shell_command:
  upgrade_hass: /home/hass/.homeassistant/extras/bash_scripts/upgrade-hass.sh

  sync_dropbox: '/home/hass/srv/bin/python /home/hass/extras/bash_scripts/dropbox_sync.py'

  github_pull: /home/hass/.homeassistant/extras/bash_scripts/pull-from-github.sh

  #github_push: /home/hass/.homeassistant/extras/bash_scripts/send-to-github.sh {{github_message}}


sensor:
  - platform: travisci
    api_key: !secret sensor_travisci
    
    
group:
  Maintenance:
    control: hidden
    entities:
      - input_boolean.maintenance_mode
      - script.upgrade_hass
      - script.github_pull
      - input_text.github_message
      - script.github_push
      - script.sync_dropbox

  Travis CI:
    - sensor.mfsocialhomeassistant_last_build_id
    - sensor.mfsocialhomeassistant_last_build_finished_at
    - sensor.mfsocialhomeassistant_last_build_state
