

tts:
  platform: google
  cache: false

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_bot_chat_id_marc
      - !secret telegram_bot_chat_id_laura
#      - !secret telegram_bot_chat_id_courtney

notify:
  - platform: telegram
    name: telegram_marc
    chat_id: !secret telegram_bot_chat_id_marc

  - platform: telegram
    name: telegram_laura
    chat_id: !secret telegram_bot_chat_id_laura

  #- platform: telegram
  #  name: telegram_courtney
  #  chat_id: !secret telegram_bot_chat_id_courtney