updater:
  include_used_components: true


sensor:
  - platform: cpuspeed

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      - type: since_last_boot
      
  - platform: version
    name: Installed HA version

  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: HA upstream
    value_template: '{{ value_json.info.version }}'
    scan_interval: 3600
