#######################################
#Resets the input_selector to 'Select'#
#when the lights are switched off     #
#######################################

alias: reset_scene_selector
initial_state: 'on'
trigger:
  platform: state
  entity_id: light.living_room
  to: 'off'
action:
  service: input_select.select_option
  data:
    entity_id: input_select.living_room_scenes
    option: Select