#######################################################################
#                                                                     #
# This package monitors any devices that report their battery level   #
# and creates a sensor for them, it then notifies me if the battery   #
# level is below 20% so that I can change them                        #
#                                                                     #
#######################################################################


automation:
  - alias: Battery alert - notification
    initial_state: on
    trigger:
      - platform: numeric_state
        entity_id:
          - sensor.bathroom_battery
          - sensor.attic_battery
          - sensor.landing_battery
          - sensor.hall_battery
          - sensor.kitchen_battery
        below: 21
    action:
      service: script.notify
      data:
        tell: adults
        no_say: 1
        message: "You have a low battery on one of your devices."

  - alias: Battery alert - Sensor (level)
    initial_state: on
    trigger:
      platform: event
      event_type: state_changed
    condition:
      - condition: template
        value_template: "{{ (trigger.event.data is not none) and (trigger.event.data.new_state is not none)
          and (trigger.event.data.new_state.attributes is not none) and (trigger.event.data.old_state is not none)
          and ('battery' not in trigger.event.data.new_state.name|lower) }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.attributes.battery_level is defined }}"
    action:
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/sensor/{{ trigger.event.data.new_state.object_id }}_battery/config"
          retain: true
          payload: >
            { "name": "{{ trigger.event.data.new_state.name }} Battery", "unit_of_measurement": "%",
              "state_topic": "homeassistant/sensor/{{ trigger.event.data.new_state.object_id }}_battery/state" }
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/sensor/{{ trigger.event.data.new_state.object_id }}_battery/state"
          retain: true
          payload: "{{ trigger.event.data.new_state.attributes.battery_level|int }}"

  - alias: Battery alert - Sensor (attribute)
    initial_state: on
    trigger:
      platform: event
      event_type: state_changed
    condition:
      - condition: template
        value_template: "{{ (trigger.event.data is not none) and (trigger.event.data.new_state is not none)
          and (trigger.event.data.new_state.attributes is not none) and (trigger.event.data.old_state is not none)
          and ('battery' not in trigger.event.data.new_state.name|lower) }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.attributes.battery is defined }}"
    action:
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/sensor/{{ trigger.event.data.new_state.object_id }}_battery/config"
          retain: true
          payload: >
            { "name": "{{ trigger.event.data.new_state.name }} Battery", "unit_of_measurement": "%" ,
              "state_topic": "homeassistant/sensor/{{ trigger.event.data.new_state.object_id }}_battery/state" }
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/sensor/{{ trigger.event.data.new_state.object_id }}_battery/state"
          retain: true
          payload: "{{ trigger.event.data.new_state.attributes.battery|int }}"

  - alias: Battery alert - Sensor (numeric)
    initial_state: on
    trigger:
      platform: event
      event_type: state_changed
    condition:
      - condition: template
        value_template: "{{ (trigger.event.data is not none) and (trigger.event.data.new_state is not none)
          and (trigger.event.data.new_state.attributes is not none) and (trigger.event.data.old_state is not none)
          and ('battery' not in trigger.event.data.new_state.name|lower) }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.attributes['Battery numeric'] is defined }}"
    action:
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/sensor/{{ trigger.event.data.new_state.object_id }}_battery/config"
          retain: true
          payload: >
            { "name": "{{ trigger.event.data.new_state.name }} Battery", "unit_of_measurement": "%",
              "state_topic": "homeassistant/sensor/{{ trigger.event.data.new_state.object_id }}_battery/state" }
      - service: mqtt.publish
        data_template:
          topic: "homeassistant/sensor/{{ trigger.event.data.new_state.object_id }}_battery/state"
          retain: true
          payload: "{{ (trigger.event.data.new_state.attributes['Battery numeric']|int + 1) * 10 }}"
