###########################################################
#                                                         #
# This package contains the components and sensors I use  #
# to monitor the Homeassistant software and system itself #
#                                                         #
###########################################################


recorder:
  db_url: !secret db_url
  purge_interval: 3
  purge_keep_days: 10


logbook: !include ../../includes/logging.yaml


history: !include ../../includes/logging.yaml


python_script:


system_health:


sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

  - platform: version
    source: docker
    beta: true


automation:
  - alias: Device - Automations status on on restart
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    action:
      service: automation.turn_on
      entity_id: all

  - alias: Device - Update Available Notifications
    trigger:
      platform: state
      entity_id: sensor.latest_version
    action:
      - delay: '00:30:00'
      - service: script.notify
        data:
          tell: mf
          call_upgrade: 1

  - alias: Device - Disk use alarm
    trigger:
      platform: numeric_state
      entity_id: sensor.disk_use_percent
      above: 85
    action:
      service: script.notify
      data:
        tell: mf
        call_hdd_space: 1

  - alias: Device - System load alarm
    trigger:
      - platform: numeric_state
        entity_id: sensor.processor_use
        above: 85
      - platform: numeric_state
        entity_id: sensor.memory_use_percent
        above: 85
    action:
      service: script.notify
      data:
        tell: mf
        call_system_load: 1

  - alias: Device - Power on
    trigger:
      platform: homeassistant
      event: start
    action:
      service: script.notify
      data:
        call_power_on: 1
        tell: mf
