###########################################
#                                         #
# This package contains the components,   #
# and sensors for monitoring the hardware #
# I have connected to my homeassistant    #
#                                         #
###########################################


homeassistant:
  customize:
    binary_sensor.washing_machine:
      icon: mdi:washing-machine

    switch.heater:
      icon: mdi:radiator

    switch.xmas_lights:
      icon: mdi:pine-tree


hue:
  bridges:
    - host: !secret hue_hub_ip
      allow_unreachable: true


light:
  platform: flux_led
  devices: !secret flux_led_devices


mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant


switch:
  platform: broadlink
  host: !secret switch_broadlink_host
  mac: !secret switch_broadlink_mac
  switches: !include_dir_merge_named ../../includes/ir_codes/


binary_sensor:
  platform: mqtt
  state_topic: "washing_machine/sensor"
  payload_on: "Running"
  payload_off: "Idle"
  name: Washing Machine


automation:
  - alias: Hardware - Heater off after 15min
    trigger:
      platform: state
      entity_id: switch.heater
      to: 'on'
      for:
        minutes: 15
    action:
      service: homeassistant.turn_off
      entity_id: switch.heater

  - alias: Hardware - Washing machine monitor
    trigger:
      platform: state
      entity_id: binary_sensor.washing_machine
      to: 'off'
      from: 'on'
    action:
      service: script.notify
      data:
        tell: adults
        message: "The washing machine has finished"
