###########################################
#                                         #
# This package contains the components,   #
# and sensors for monitoring the hardware #
# I have connected to my homeassistant    #
#                                         #
###########################################


homeassistant:
  customize:
    binary_sensor.washing_machine:
      icon: mdi:washing-machine

    switch.heater:
      icon: mdi:radiator

    switch.xmas_lights:
      icon: mdi:pine-tree


hue:
  bridges:
    - host: !secret hue_hub_ip
      allow_unreachable: true


light:
  platform: flux_led
  devices: !secret flux_led_devices


cast:


media_player:
  - platform: virgintivo
    tivos:
      1:
        name: Virgin
        host: !secret virgin_host
    guide:
      picture_refresh: 30
    channels: !include ../../includes/virgin_channels.yaml

  - platform: kodi
    name: Kodi
    host: !secret kodi_host
    port: !secret kodi_port
    enable_websocket: false
    username: !secret kodi_username
    password: !secret kodi_password
    turn_off_action:
      service: media_player.kodi_call_method
      data_template:
        entity_id: "{{ entity_id }}"
        method: System.Shutdown


mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant


switch:
  - platform: tplink
    host: !secret switch_tplink_heater

  - platform: tplink
    host: !secret switch_tplink_xmas

  - platform: broadlink
    host: !secret switch_broadlink_host
    mac: !secret switch_broadlink_mac
    switches: !include_dir_merge_named ../../includes/ir_codes/

binary_sensor:
  platform: mqtt
  state_topic: "washing_machine/sensor"
  payload_on: "Running"
  payload_off: "Idle"
  name: Washing Machine


automation:
  - alias: Hardware - Heater off after 15min
    initial_state: on
    trigger:
      platform: state
      entity_id: switch.heater
      to: 'on'
    action:
      - delay: 00:15:00
      - service: homeassistant.turn_off
        entity_id: switch.heater

  - alias: Hardware - Washing machine monitor
    initial_state: on
    trigger:
      platform: state
      entity_id: binary_sensor.washing_machine
      to: 'off'
      from: 'on'
    action:
      service: script.notify
      data:
        tell: adults
        message: "The washing machine has finished"
