################################################
#                                              #
# This package creates a device that allows me #
# to set a boolean to show the system in       #
# "Maintenance Mode", and manage backing up,   #
# upgrading and pulling config from Github     #
#                                              #
################################################


custom_updater:
  track:
    - cards
    - components
  card_urls:
    - https://raw.githubusercontent.com/kalkih/mini-media-player/master/tracker.json


weblink:
  entities:
    - name: Github
      url: https://github.com/mf-social/Home-Assistant
    - name: Configure Alexa
      url: https://alexa.amazon.co.uk/spa/index.html#smart-home
    - name: Dropbox
      url: https://dropbox.com
    - name: Router
      url: !secret weblink_router
    - name: Uptime Robot
      url: https://uptimerobot.com

switch:
  platform: template
  switches:
    debug:
      friendly_name: Show Debug View
      value_template: "{{ is_state_attr('group.debug' , 'view' , true) }}"
      turn_on:
        - service: python_script.populate_catchall_group
        - service: python_script.find_dead_items
        - service: group.set
          data:
            object_id: debug
            view: true
            visible: true
      turn_off:
        - service: group.set
          data:
            object_id: debug
            view: false
            visible: false
        - service: group.remove
          data:
            object_id: catchall
        - service: group.remove
          data:
            object_id: deaditems


input_boolean:
  maintenance_mode:
    name: Maintenance mode
    icon: mdi:auto-fix


input_text:
  github_message:
    name: Commit Message
    initial: Push from local


shell_command:
  upgrade_hass: /extras/bash_scripts/upgrade-hass.sh

  github_pull: /extras/bash_scripts/pull-from-github.sh

  github_push: /extras/bash_scripts/send-to-github.sh "{{ states('input_text.github_message') }}"

  sync_dropbox: /extras/bash_scripts/sync-dropbox.sh "{{ token }}" "{{ url }}"

  quick_restart: sudo systemctl restart home-assistant@homeassistant.service


alert:
  maintenance_mode_alert:
    name: Maintenance Mode has been on for a long time
    done_message: Maintenance Mode de-activated
    entity_id: input_boolean.maintenance_mode
    repeat:
      - 60
    skip_first: true
    notifiers:
      - adults

automation:
  # TODO - Perform a backup automatically
  # TODO - Status check
  - alias: Maintenance - Notify when backups completed
    initial_state: on
    trigger:
      platform: event
      event_type: done_sync
    action:
      service: notify.mf
      data:
        message: "The dropbox sync has finished."

script:
  upgrade_hass:
    alias: ' '
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.maintenance_mode
      - delay: 00:00:02
      - service: shell_command.upgrade_hass

  github_pull:
    alias: ' '
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.maintenance_mode
      - delay: 00:00:02
      - service: shell_command.github_pull

  github_push:
    alias: ' '
    sequence:
      - condition: template
        value_template: "{{ not is_state('input_text.github_message' , '' ) }}"
      - service: shell_command.github_push
      - service: persistent_notification.create
        data:
          notification_id: "Github_push_alert"
          title: "Github"
          message: "You have pushed your local files to github, you must merge the branches on github then sync the master branch here."

  sync_dropbox:
    alias: ' '
    sequence:
      - service: shell_command.sync_dropbox
        data:
          token: !secret done_token
          url: !secret done_url

  quick_restart:
    alias: ' '
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.maintenance_mode
      - delay: 00:00:02
      - service: shell_command.quick_restart

  learn_ir:
    alias: ' '
    sequence:
      - service: !secret learn_ir
