################################################
#                                              #
# This package creates a device that allows me #
# to set a boolean to show the system in       #
# "Maintenance Mode", and manage backing up,   #
# upgrading and pulling config from Github     #
#                                              #
################################################


switch:
  platform: template
  switches:
    debug:
      friendly_name: Show Debug View
      value_template: "{{ is_state_attr('group.debug' , 'view' , true) }}"
      turn_on:
        - service: python_script.populate_catchall_group
        - service: python_script.find_dead_items
        - service: group.set
          data:
            object_id: debug
            view: true
            visible: true
      turn_off:
        - service: group.set
          data:
            object_id: debug
            view: false
            visible: false
        - service: group.remove
          data:
            object_id: catchall
        - service: group.remove
          data:
            object_id: deaditems


input_boolean:
  maintenance_mode:
    name: Maintenance mode
    icon: mdi:auto-fix


input_text:
  github_message:
    name: Commit Message
    initial: Push from local


shell_command:
  #TODO - these now need to be SSH....
  upgrade_system: ssh.../upgrade-system.sh

  github_sync: ssh.../sync-from-github.sh

  github_send: ssh.../send-to-github.sh "{{ states('input_text.github_message') }}"

  backup_sync: ssh.../zip-dropbox.sh "{{ token }}" "{{ url }}"

  quick_restart: ssh.../DOCKER_RESTART


alert:
  maintenance_mode_alert:
    name: Maintenance Mode has been on for a long time
    done_message: Maintenance Mode de-activated
    entity_id: input_boolean.maintenance_mode
    repeat:
      - 60
    skip_first: true
    notifiers:
      - adults

automation:
  - alias: Maintenance - Backup system to Dropbox and NAS
    initial_state: on
    trigger:
      platform: time
      at: '19:00:00'
    condition:
      condition: time
      weekday:
        - sun
    action:
      service: script.backup_sync

  - alias: Maintenance - Notify when backups completed
    initial_state: on
    trigger:
      platform: event
      event_type: done_sync
    action:
      service: notify.mf
      data:
        message: "The backup has finished."

script:
  upgrade_system:
    alias: ' '
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.maintenance_mode
      - delay: 00:00:02
      - service: shell_command.upgrade_system

  github_sync:
    alias: ' '
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.maintenance_mode
      - delay: 00:00:02
      - service: shell_command.github_sync

  github_send:
    alias: ' '
    sequence:
      - condition: template
        value_template: "{{ not is_state('input_text.github_message' , '' ) }}"
      - service: shell_command.github_send
      - service: persistent_notification.create
        data:
          notification_id: "github_send_alert"
          title: "Github"
          message: "You have pushed your local files to github, you must merge the branches on github then sync the master branch here."

  backup_sync:
    alias: ' '
    sequence:
      - service: shell_command.backup_sync
        data:
          token: !secret done_token
          url: !secret done_url

  quick_restart:
    alias: ' '
    sequence:
      - service: homeassistant.turn_on
        entity_id: input_boolean.maintenance_mode
      - delay: 00:00:02
      - service: shell_command.quick_restart

  learn_ir:
    alias: ' '
    sequence:
      - service: !secret learn_ir
