###########################################
#Switches away mode and holiday mode off  #
#when the guest mode is activated         #
###########################################

alias: 'Reset occupancy booleans - guest'
initial_state: 'on'
trigger:
  platform: state
  entity_id: input_boolean.guest_mode
  to: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.away_mode