################################
#A one-touch scene controller  #
################################

name: Livingroom movie
entities:
  light.living_room:
    state: on
    transition: 4
    brightness: 35