################################
#A one-touch scene controller  #
################################

name: Livingroom sunset
entities:
  light.living_room:
    state: on
    transition: 600
    brightness: 255