################################
#A one-touch scene controller  #
################################

name: Livingroom bright
entities:
  light.living_room:
    state: on
    transition: 3
    brightness: 255