################################
#A one-touch scene controller  #
################################

name: Livingroom dim
entities:
  light.living_room:
    state: on
    transition: 4
    brightness: 125