#########################################
# A script that sets the bedroom lights #
# to a romantic scene and then plays    #
# some romatic music over the chromecast#
# you know, just because it's a thing   #
#########################################

romance:
  alias: Romance Mode
  sequence:
    - service: light.hue_activate_scene
      data:
        group_name: "Master Bedroom"
        scene_name: "Spring blossom"
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroomcca
        volume_level: '0.20'
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroomcca
        media_content_id: !secret romance_track1
        media_content_type: 'audio/mp4'
    - delay: '00:03:39'
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroomcca
        media_content_id: !secret romance_track2
        media_content_type: 'audio/mp4'
    - delay: '00:04:29'
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroomcca
        media_content_id: !secret romance_track3
        media_content_type: 'audio/mp4'
    - delay: '00:03:17'
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroomcca
        media_content_id: !secret romance_track4
        media_content_type: 'audio/mp4'
    - delay: '00:02:58'
    - service: media_player.play_media
      data:
        entity_id: media_player.bedroomcca
        media_content_id: !secret romance_track5
        media_content_type: 'audio/mp4'