###################################################
#                                                 #
# This package contains the components I use to   #
# notify, and be notified by, homeassistant       #
# and an engine that translates the notifications #
# in to text messages and to TTS (see include)    #
#                                                 #
###################################################


tts:
  platform: picotts
  language: 'en-GB'


telegram_bot:
  platform: polling
  api_key: !secret telegram_bot_api_key
  parse_mode: html
  allowed_chat_ids:
    - !secret telegram_bot_chat_id_mf
    - !secret telegram_bot_chat_id_ls
#TODO - ...
#    - !secret telegram_bot_chat_id_cg


notify:
  - platform: telegram
    name: mf
    chat_id: !secret telegram_bot_chat_id_mf

  - platform: telegram
    name: ls
    chat_id: !secret telegram_bot_chat_id_ls
#TODO - ...
  #- platform: telegram
  #  name: cg
  #  chat_id: !secret telegram_bot_chat_id_ccg
  #
  # - platform: group
  #   name: all
  #   services:
  #     - service: mf
  #     - service: ls
  #     - service: cg

  - platform: group
    name: adults
    services:
      - service: mf
      - service: ls

binary_sensor:
  platform: random


script:
  notify:
    sequence:
      - service: script.message
        data_template: !include ../../extras/includes/notify_engine.yaml

  message:
    sequence:
      - service: script.announce
        data_template:
          media_player: '{{ media_player }}'
          message: '{{ message }}'
      - service: script.text
        data_template:
          who: '{{ who }}'
          message: '{{ message }}'
#TODO - ...
      # - service: on_screen
      #   data_template:
      #     message: '{{ message }}'

  announce:
    sequence:
#TODO - ....
      # - condition: [when to not announce]
      - service: media_player.volume_set
        data_template:
          entity_id: '{{ media_player }}'
          volume_level: >
            {% if now().hour < 7 or now().hour > 22 %} 0.2
            {% elif now().hour > 7 or now().hour < 9 %} 0.3
            {% else %} 0.4 {% endif %}
      - service: tts.picotts_say
        data_template:
          entity_id: '{{ media_player }}'
          message: '{{ message | replace("\n"," ") | replace("   "," ") | replace("  "," ") }}'

  text:
    sequence:
#TODO - ....
      # - condition: [when to not send a text]
      - service_template: '{{ who }}'
        data_template:
          message: '{{ message | replace("\n"," ") | replace("   "," ") | replace("  "," ") }}'
          data:
            keyboard:
              - '/status'
              - '/maintenance'

#TODO ...
  # on_screen: [when to add a persistent notification]
