#########################################################
#                                                       #
# This package contains automations that send reminders #
#                                                       #
# DEPENDS ON: Occupancy                                 #
#                                                       #
#########################################################


automation:
  - alias: Reminder - Bin day
    initial_state: on
    trigger:
      platform: time
      at: '18:15:00'
    condition:
      - condition: time
        weekday:
          - wed
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'off'
    action:
    #TODO...
      - wait_template: "{{(states.group.adults.state == 'home')}}"
      - delay: 00:15:00
      - service: script.notify
        data:
          tell: adults
          message: "The bins need to go out tonight."
