#########################################################
#                                                       #
# This package contains automations that send reminders #
#                                                       #
# DEPENDS ON: Occupancy                                 #
#                                                       #
#########################################################

automation:
  - alias: Bin day reminder
    initial_state: 'on'
    trigger:
      platform: time
      at: '18:15:00'
    condition:
      - condition: time
        weekday:
          - wed
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: 'off'
    action:
#      - wait_template: "{{(states.sensor.tracker_status.state == 'MF_LS_CG') or (states.sensor.tracker_status.state == 'MF_LS') or (states.sensor.tracker_status.state == 'MF_CG') or (states.sensor.tracker_status.state == 'LS_CG') or (states.sensor.tracker_status.state == 'MF') or (states.sensor.tracker_status.state == 'LS')}}"
#      - delay: 00:15:00
      - service: tts.google_say
        entity_id: media_player.everywhere
        data:
          message: 'The bins need to go out tonight.'