########################################################
#                                                      #
# This package contains automations that respond to    #
# interactive commands with system/general information #
#                                                      #
# DEPENDS ON: Notifications                            #
#                                                      #
########################################################


automation:
  - alias: Telegram - Reply with Status
    initial_state: 'on'
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/status'
    action:
      service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: "System is online!


          Last system reboot was on {{states.sensor.last_boot.state}}.


          Currently home is {{states.sensor.home_status.state}}.

          Marc is {{states.device_tracker.forthygpixel.state}}.

          Laura is {{states.device_tracker.lauras_iphone.state}}.

          Courtney is {{states.device_tracker.iphone.state}}.

          Guest mode is {{states.input_boolean.guest_mode.state}}.


          The alarm is {{states.alarm_control_panel.alarm.state}}.


          The lights group is {{states.group.all_lights.state}}

          Living room lights are {{states.light.living_room.state}}.

          Landing lights are {{states.light.landing.state}}.

          Master bedroom lights are {{states.light.bedroom.state}}."
        keyboard: ["/lights, /occupancy", "/menu"]

  - alias: Telegram - Reply with Occupancy
    initial_state: 'on'
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/occupancy'
    action:
      service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: 'Currently home is {{states.sensor.home_status.state}}.

          Marc is {{states.device_tracker.forthygpixel.state}}.

          Laura is {{states.device_tracker.lauras_iphone.state}}.

          Courtney is {{states.device_tracker.iphone.state}}.

          Guest mode is {{states.input_boolean.guest_mode.state}}.'
        keyboard: ["/away, /holiday" , "/guest, /lights", "/menu"]

  - alias: Telegram - Reply with Menu
    initial_state: 'on'
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/menu'
    action:
      service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: 'Commands...'
        keyboard: ["/lights, /occupancy", "/status"]

  - alias: Telegram - Reply with Lights
    initial_state: 'on'
    trigger:
      platform: event
      event_type: telegram_command
      event_data:
        command: '/lights'
    action:
      service: telegram_bot.send_message
      data_template:
        target: '{{ trigger.event.data.user_id }}'
        message: 'The lights group is {{states.group.all_lights.state}}

          Living room lights are {{states.light.living_room.state}}.

          Landing lights are {{states.light.landing.state}}.

          Master bedroom lights are {{states.light.bedroom.state}}.'
        keyboard: ["/onALL, /LivingRoom", "/offALL, /Bedroom", "/menu"]
