##########################################################
#                                                        #
# This package contains the components and UI elements I #
# use to configure the homeassistant web-based interface #
#                                                        #
##########################################################


http:
  api_password: !secret api_password
  ip_ban_enabled: True
  login_attempts_threshold: 3


config:


panel_iframe:
  kodi:
    title: 'Kodi'
    url: !secret iframe_kodi_url
    icon: mdi:kodi

  nodered:
    title: 'Node-Red'
    url: !secret iframe_nodered_url
    icon: mdi:shuffle-variant


frontend:
  javascript_version: auto
  themes: !include_dir_merge_named ../../extras/includes/themes/
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-mini-media-player.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
    - /local/custom_ui/state-card-mini-media-player_es5.html


customizer:
  custom_ui: hosted


automation:
  alias: Interface - Set UI theme
  initial_state: on
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id:
        - alarm_control_panel.alarm
        - input_boolean.maintenance_mode
        - sensor.dark_outside
    - platform: time
      at: '23:00:00'
  action:
    service: frontend.set_theme
    data_template:
      name: >
        {% if not is_state ('alarm_control_panel.alarm' , 'disarmed') %} darkred
        {% elif is_state ('input_boolean.maintenance_mode' , 'on') %} darkorange
        {% elif ((now().hour == 23) or (now().hour < 7)) %} darkcyan
        {% elif (states.sensor.dark_outside.state == "true") %} midnight
        {% else %} default {% endif %}
