###########################################################
#                                                         #
# This package contains the components I use to configure #
# and access the homeassistant web-based interface        #
#                                                         #
###########################################################


homeassistant:
  customize_glob:
    sensor.hline_*:
     custom_ui_state_card: state-card-hline

  customize:
    group.av:
      order: 1

    group.media:
      order: 2

    group.bedroom:
      order: 3

    group.boys_room:
      order: 4

    group.girls_room:
      order: 5

    group.tools:
      order: 6


http:
  api_password: !secret api_password
  ip_ban_enabled: True
  login_attempts_threshold: 3
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url


duckdns:
  domain: !secret domain
  access_token: !secret access_token


frontend:
  javascript_version: auto
  themes: !include_dir_merge_named ../../extras/includes/themes/
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-mini-media-player.html
    - /local/custom_ui/state-card-hline.html
    - /local/custom_ui/state-card-script-custom-text.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
    - /local/custom_ui/state-card-mini-media-player_es5.html
    - /local/custom_ui/state-card-hline_es5.html
    - /local/custom_ui/state-card-script-custom-text-es5.html


config:


customizer:
  custom_ui: hosted


sensor:
  - platform: command_line
    name: SSL cert expiry
    unit_of_measurement: days
    scan_interval: 10800
    command: !secret ssl_command

  - platform: rest
    resource: https://raw.githubusercontent.com/c727/home-assistant-tiles/master/LATEST_VERSION
    name: UI Tiles version
    scan_interval: 3600

  - platform: template
    sensors:
      hline_1:
        value_template: hline
      hline_2:
        value_template: hline
      hline_3:
        value_template: hline


group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.occupancy
      - group.tiles_lights

  av:
    view: yes
    icon: mdi:television-classic
    entities:
      - group.tiles_av_remote
      - group.tiles_tv_remote
      - group.tiles_bluray_remote
      - group.tiles_cctv_remote

  media:
    view: yes
    icon: mdi:speaker-wireless
    entities:
      - group.music
      - group.tiles_media

  bedroom:
    view: yes
    icon: mdi:hotel
    entities: group.tiles_bedroom

  boys_room:
    view: yes
    icon: mdi:human-handsdown
    entities: group.tiles_boys

  girls_room:
    view: yes
    icon: mdi:human-female
    entities: group.tiles_girls

  tools:
    view: yes
    icon: mdi:wrench
    entities:
      - group.maintenance
      - group.configure_external
      - group.zwave
      - group.batteries
      - group.all_alarm_clock


shell_command:
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01


automation:
  - alias: Interface - Set UI theme
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id:
          - alarm_control_panel.alarm
          - input_boolean.maintenance_mode
      - platform: state
        entity_id: input_boolean.dark
      - platform: time
        at: '23:00:00'
      - platform: time
        at: '07:00:00'
    action:
      service: frontend.set_theme
      data_template:
        name: >
          {% if not is_state ('alarm_control_panel.alarm' , 'disarmed') %} darkred
          {% elif is_state ('input_boolean.maintenance_mode' , 'on') %} darkorange
          {% elif ((now().hour == 23) or (now().hour < 7)) %} darkcyan
          {% elif is_state('input_boolean.dark' , 'on') %} midnight
          {% else %} default {% endif %}

  - alias: Interface - UI Tiles update available
    trigger:
      platform: state
      entity_id: sensor.ui_tiles_version
    action:
      service: script.notify
      data:
        no_say: 1
        tell: mf
        call_tiles_update: 1

  - alias: Interface - Renew SSL certificate
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 29
    action:
      service: shell_command.renew_ssl

  - alias: Interface - SSL certificate expiry notification
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id: sensor.ssl_cert_expiry
      below: 21
    action:
      service: script.notify
      data:
        tell: mf
        no_say: 1
        message: 'Warning - SSL certificate expires in 21 days and has not been automatically renewed'
