##########################################################
#                                                        #
# This package contains the components and UI elements I #
# use to configure the homeassistant web-based interface #
#                                                        #
##########################################################


http:
  api_password: !secret api_password
  ip_ban_enabled: True
  login_attempts_threshold: 3


config:


logbook:


history:


panel_iframe:
  kodi:
    title: 'Kodi'
    url: !secret iframe_kodi_url
    icon: mdi:kodi


frontend:
  javascript_version: auto
  themes: !include ../../extras/includes/themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-mini-media-player.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
    - /local/custom_ui/state-card-mini-media-player_es5.html


customizer:
  custom_ui: hosted


automation:
  alias: Set UI theme
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.dark_outside
    - platform: time
      at: '23:00:00'
  action:
    - service_template: frontend.set_theme
      data_template:
        name: >-
          {% if (now().hour == 23) %} darkcyan
          {% elif (states.sensor.dark_outside.state == "true") %} midnight
          {% else %} default {% endif %}
