homeassistant:
  customize:
    input_text.lights:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tile_remotes/lights.yaml

    input_text.bedroom:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tile_remotes/bedroom.yaml

    input_text.tv_remote:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tile_remotes/tv_remote.yaml


script: !include ../../extras/includes/tile_remotes/script.yaml


input_text:
  lights:
    name: lights

  bedroom:
    name: bedroom

  tv_remote:
    name: tv_remote


group:
  tiles_lights:
    name: Lights
    entities:
      - input_text.lights

  tiles_bedroom:
    name: Bedroom
    entities:
      - input_text.bedroom

  tiles_tv_remote:
    name: TV remote
    entities:
      - input_text.tv_remote
