homeassistant:
  customize:
    input_text.lights:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tile_remotes/lights.yaml

    input_text.bedroom:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tile_remotes/bedroom.yaml

    input_text.tv_remote:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tile_remotes/tv_remote.yaml

    input_text.boys:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tile_remotes/boys.yaml

    input_text.girls:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tile_remotes/girls.yaml


script: !include ../../extras/includes/tile_remotes/script.yaml

input_boolean:
  remote_masterbed_radio:
  
  remote_boys_radio:

  remote_girls_radio:

input_text:
  lights:
    name: lights

  bedroom:
    name: bedroom

  tv_remote:
    name: tv_remote

  boys:
    name: boys

  girls:
    name: girls


group:
  tiles_lights:
    name: Lights
    entities:
      - input_text.lights

  tiles_bedroom:
    name: Bedroom
    entities:
      - input_select.master_bedroom_scenes
      - input_text.bedroom

  tiles_tv_remote:
    name: TV remote
    entities:
      - input_text.tv_remote

  tiles_boys:
    name: Boys
    entities:
      - input_text.boys

  tiles_girls:
    name: Girls
    entities:
     - input_text.girls

automation:
  - alias: 'remote radio masterbed on'
    trigger:
      platform: state
      entity_id: input_boolean.remote_masterbed_radio
      to: 'on'
    action:
      service: script.remote_masterbed_radio

  - alias: 'remote radio boys on'
    trigger:
      platform: state
      entity_id: input_boolean.remote_boys_radio
      to: 'on'
    action:
      service: script.remote_boys_radio

  - alias: 'remote radio girls on'
    trigger:
      platform: state
      entity_id: input_boolean.remote_girls_radio
      to: 'on'
    action:
      service: script.remote_girls_radio

  - alias: 'remote radio masterbed off'
    trigger:
      platform: state
      entity_id: input_boolean.remote_masterbed_radio
      to: 'off'
    action:
      service: media_player.turn_off
      entity_id: media_player.bedroom

  - alias: 'remote radio boys off'
    trigger:
      platform: state
      entity_id: input_boolean.remote_boys_radio
      to: 'off'
    action:
      service: media_player.turn_off
      entity_id: media_player.boys

  - alias: 'remote radio girls off'
    trigger:
      platform: state
      entity_id: input_boolean.remote_girls_radio
      to: 'off'
    action:
      service: media_player.turn_off
      entity_id: media_player.girls