#######################################################
#                                                     #
# This package configures the custom-ui-tiles I use   #
# in the frontend, the configuration is long so it is #
# split in to includes, and the scripts in this       #
# configuration are purely for one-touch purposes in  #
# the UI, such as remotes or 'quick' settings         #
#                                                     #
#######################################################


homeassistant:
  customize:
    input_text.lights:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tiles/lights.yaml

    input_text.bedroom:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tiles/bedroom.yaml

    input_text.boys:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tiles/boys.yaml

    input_text.girls:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tiles/girls.yaml

    input_text.av_remote:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tiles/av_remote.yaml

    input_text.tv_remote:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tiles/tv_remote.yaml

    input_text.bluray_remote:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tiles/bluray_remote.yaml

    input_text.cctv_remote:
      custom_ui_state_card: state-card-tiles
      config: !include ../../extras/includes/tiles/cctv_remote.yaml


input_boolean:
  remote_bedroom_radio:

  remote_boys_radio:

  remote_girls_radio:

input_text:
  lights:
    name: lights

  bedroom:
    name: bedroom

  boys:
    name: boys

  girls:
    name: girls

  av_remote:
    name: av_remote

  tv_remote:
    name: tv_remote

  bluray_remote:
    name: bluray_remote

  cctv_remote:
    name: cctv_remote


group:
  tiles_lights:
    name: Lights
    entities:
      - input_text.lights

  tiles_bedroom:
    name: Bedroom
    entities:
      - input_select.bedroom_scenes
      - input_text.bedroom
      - input_text.media_bedroom

  tiles_boys:
    name: Boys
    entities:
      - input_text.boys
      - input_text.media_boys

  tiles_girls:
    name: Girls
    entities:
     - input_text.girls
     - input_text.media_girls

  tiles_av_remote:
    name: AV remote
    entities:
      - input_text.av_remote

  tiles_tv_remote:
    name: TV remote
    entities:
      - input_text.tv_remote

  tiles_bluray_remote:
    name: Blu-Ray remote
    entities:
      - input_text.bluray_remote

  tiles_cctv_remote:
    name: CCTV remote
    entities:
      - input_text.cctv_remote


automation: !include ../../extras/includes/tiles/automation.yaml

script: !include ../../extras/includes/tiles/script.yaml
