###########################################
#                                         #
# This package contains the configuration #
# for the view groups used in the UI      #
#                                         #
###########################################


homeassistant:
  customize:
    group.downstairs:
      order: 1

    group.av:
      order: 2

    group.media:
      order: 3

    group.bedroom:
      order: 4

    group.boys_room:
      order: 5

    group.girls_room:
      order: 6

    group.tools:
      order: 7


group:
  default_view:
    view: yes
    icon: mdi:sofa
    entities:
      - group.tiles_lights
      - group.quick_timer
      - group.downstairs_alarm_clock

  av:
    view: yes
    icon: mdi:television-classic
    entities:
      - group.tiles_av_remote
      - group.tiles_tv_remote
      - group.tiles_bluray_remote

  media:
    view: yes
    icon: mdi:speaker-wireless
    entities:
      - group.music
      - group.tiles_media

  bedroom:
    view: yes
    icon: mdi:hotel
    entities:
      - group.tiles_bedroom
      - group.bedroom_alarm_clock

  boys_room:
    view: yes
    icon: mdi:human-handsdown
    entities:
      - group.tiles_boys
      - group.boys_alarm_clock

  girls_room:
    view: yes
    icon: mdi:human-female
    entities:
      - group.tiles_girls
      - group.girls_alarm_clock

  tools:
    view: yes
    icon: mdi:wrench
    entities:
      - group.maintenance
      - group.occupancy_modes
      - group.home_modes
      - group.all_alarm_clock
      - group.configure_external
      - group.batteries
