###########################################
#                                         #
# This package contains the configuration #
# for the view groups used in the UI      #
#                                         #
###########################################


homeassistant:
  customize:
    group.all_automations:
      hidden: false

    group.all_scripts:
      hidden: false
      control: hidden

    group.downstairs:
      order: 1

    group.media:
      order: 2

    group.master_bedroom:
      order: 3

    group.boys_room:
      order: 4

    group.girls_room:
      order: 5

    group.tools:
      order: 6

    group.information:
      order: 7

    group.security:
      order: 8

    group.settings:
      order: 9

    group.remote:
      order: 10


group:
  downstairs:
    view: yes
    name: Downstairs
    icon: mdi:sofa
    entities:
      - group.livingroom_lights
      - group.downstairs_alarm_clock
      - media_player.living_room_kodi
      - media_player.livingroom
      - media_player.kitchen
      - media_player.downstairs

  media:
    view: yes
    name: Media
    icon: mdi:speaker-wireless
    entities:
      - media_player.living_room_kodi
      - media_player.kitchen
      - media_player.bedroom
      - media_player.livingroom
      - media_player.boys
      - media_player.girls      
      - media_player.everywhere
      - media_player.downstairs
      - media_player.kids
      - group.music

  master_bedroom:
    view: yes
    name: Master Bedroom
    icon: mdi:hotel
    entities:
      - group.master_bedroom_lights
      - group.smart_switch
      - group.masterbed_alarm_clock
      - group.masterbed_moods
      - media_player.bedroom

  boys_room:
    view: yes
    name: Boys Room
    icon: mdi:human-handsdown
    entities:
      - group.boys_alarm_clock
      - media_player.boys

  girls_room:
    view: yes
    name: Girls Room
    icon: mdi:human-female
    entities:
      - group.girls_alarm_clock
      - media_player.girls

  tools:
    view: yes
    name: Tools
    icon: mdi:wrench
    entities:
      - group.maintenance
      - group.travis_ci
      - group.occupancy_modes
      - group.home_modes
      - group.other_lights
      - group.all_lights
      - group.quick_timer
      - group.all_alarm_clock
      - group.configure_external

  information:
    view: yes
    name: Information
    icon: mdi:information-variant
    entities:
      - group.phone_trackers
      - group.environment
      - group.weather_alerts
      - group.calendar
      - group.system
      - group.hue
      - group.devices
      - group.mqtt
      - group.time
      - group.zwave

  security:
    view: yes
    name: Security
    icon: mdi:security
    entities:
      - group.alarm
      - group.motion_sensors
      - group.email_security

  settings:
    view: yes
    name: Settings
    icon: mdi:settings
    entities:
      - group.all_automations
      - group.all_scripts

  remote:
    view: yes
    name: Remote
    entities:
      - group.tiles_living_room
      - group.tiles_bedroom
      - group.tiles_tv_remote