###########################################
#                                         #
# This package contains the configuration #
# for the view groups used in the UI      #
#                                         #
###########################################


homeassistant:
  customize:
    group.av:
      order: 1

    group.media:
      order: 2

    group.bedroom:
      order: 3

    group.boys_room:
      order: 4

    group.girls_room:
      order: 5

    group.tools:
      order: 6


group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.occupancy
      - group.tiles_lights

  av:
    view: yes
    icon: mdi:television-classic
    entities:
      - group.tiles_av_remote
      - group.tiles_tv_remote
      - group.tiles_bluray_remote
      - group.tiles_cctv_remote

  media:
    view: yes
    icon: mdi:speaker-wireless
    entities:
      - group.music
      - group.tiles_media

  bedroom:
    view: yes
    icon: mdi:hotel
    entities: group.tiles_bedroom

  boys_room:
    view: yes
    icon: mdi:human-handsdown
    entities: group.tiles_boys

  girls_room:
    view: yes
    icon: mdi:human-female
    entities: group.tiles_girls

  tools:
    view: yes
    icon: mdi:wrench
    entities:
      - group.maintenance
      - group.configure_external
      - group.batteries
      - group.all_alarm_clock
