#########################################
#                                       #
# This include contains the automations #
# used by the tile cards                #
#                                       #
#########################################


- alias: Remote - Radio bedroom
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.remote_bedroom_radio
  action:
    service_template: >
      {% if is_state('input_boolean.remote_bedroom_radio' , 'on') %} homeassistant.turn_on
      {% else %} homeassistant.turn_off {% endif %}
    data_template:
      entity_id: >
        {% if is_state('input_boolean.remote_bedroom_radio' , 'on') %} script.remote_bedroom_radio
        {% else %} media_player.bedroom {% endif %}

- alias: Remote - Radio boys
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.remote_boys_radio
  action:
    service_template: >
      {% if is_state('input_boolean.remote_boys_radio' , 'on') %} homeassistant.turn_on
      {% else %} homeassistant.turn_off {% endif %}
    data_template:
      entity_id: >
        {% if is_state('input_boolean.remote_boys_radio' , 'on') %} script.remote_boys_radio
        {% else %} media_player.boys {% endif %}


- alias: Remote - Radio girls
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.remote_girls_radio
  action:
    service_template: >
      {% if is_state('input_boolean.remote_girls_radio' , 'on') %} homeassistant.turn_on
      {% else %} homeassistant.turn_off {% endif %}
    data_template:
      entity_id: >
        {% if is_state('input_boolean.remote_girls_radio' , 'on') %} script.remote_girls_radio
        {% else %} media_player.girls {% endif %}

- alias: Remote - Bluray power tracker
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.bluray_power
  action:
    service: homeassistant.toggle
    data_template:
      entity_id: switch.bluray_power_toggle

- alias: Remote - Kodi power tracker
  initial_state: on
  trigger:
    platform: state
    entity_id: input_boolean.kodi_power
  action:
    service_template: >
      {% if is_state('input_boolean.kodi_power','on') %} homeassistant.turn_on
      {% else %} homeassistant.turn_off {% endif %}
    entity_id: media_player.kodi
