#########################################
#                                       #
# This include contains the automations #
# used by the tile cards                #
#                                       #
#########################################


- alias: Remote radio bedroom on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.remote_bedroom_radio
    to: 'on'
  action:
    service: script.remote_bedroom_radio

- alias: Remote radio boys on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.remote_boys_radio
    to: 'on'
  action:
    service: script.remote_boys_radio

- alias: Remote radio girls on
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.remote_girls_radio
    to: 'on'
  action:
    service: script.remote_girls_radio

- alias: Remote radio bedroom off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.remote_bedroom_radio
    to: 'off'
  action:
    service: media_player.turn_off
    entity_id: media_player.bedroom

- alias: Remote radio boys off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.remote_boys_radio
    to: 'off'
  action:
    service: media_player.turn_off
    entity_id: media_player.boys

- alias: Remote radio girls off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.remote_girls_radio
    to: 'off'
  action:
    service: media_player.turn_off
    entity_id: media_player.girls