#####################################
#Converts Away mode to Holiday mode #
#if away for longer than 48 hours   #
#####################################

alias: 'Set Holiday Mode'
initial_state: 'on'
trigger:
  platform: state
  entity_id: input_boolean.away_mode
  to: 'on'
  for:
    hours: 48
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.holiday_mode
  - service: input_boolean.turn_off
    entity_id: input_boolean.away_mode