#################################
#Placing entities on the card   #
#################################

master_bedroom_lights:
  name: Lights
  entities:
    - light.mb_ceiling
    - light.mb_stairs
    - input_select.master_bedroom_scenes

livingroom_lights:
  name: Lights
  entities:
    - light.lr_left
    - light.lr_room_right
    - input_select.living_room_scenes

other_lights:
  name: Lights
  control: hidden
  entities:
    - light.landing
    - light.bathroom