#################################
#Placing entities on the card   #
#################################

System:
  - updater.updater
  - sensor.installed_ha_version
  - sensor.ha_upstream
  - sensor.ssl_cert_expiry
  - sensor.cpu_speed
  - sensor.cpu_used
  - sensor.disk_used_
  - sensor.last_boot
  - sensor.ram_used
  - sensor.since_last_boot

Maintenance:
  control: hidden
  entities:
    - input_boolean.maintenance_mode
    - script.upgrade_hass
    - script.github_pull
    - script.github_push
    - input_text.github_message
    - script.sync_dropbox

Travis CI:
  - sensor.mfsocialhomeassistant_last_build_id
  - sensor.mfsocialhomeassistant_last_build_finished_at
  - sensor.mfsocialhomeassistant_last_build_state