############################################################
#                                                          #
#  This package creates the 'moods' for the Master Bedroom #
#                                                          #
############################################################


homeassistant:
  customize:
#    script.romance:
#      can_cancel: false
#      icon: mdi:creation

    script.lullaby:
      can_cancel: false
      icon: mdi:creation


group:
  masterbed_moods:
    name: Moods
    control: hidden
    entities:
      - script.lullaby
#      - script.romance


script:
  lullaby:
    alias: Lullaby Mode
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: '0.20'
      - service: media_player.play_media
        data:
          entity_id: media_player.bedroom
          media_content_id: http://37.59.28.208:8543/stream
          media_content_type: 'audio/mp4'
      - service: hue.hue_activate_scene
        data:
          group_name: "Master Bedroom"
          scene_name: "Nightlight"
      - service: light.turn_off
        entity_id: light.bedroom_stairs
      - delay: '00:15:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: '0.15'
      - delay: '00:15:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: '0.10'
      - delay: '00:15:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: '0.05'
      - delay: '00:15:00'
      - service: media_player.turn_off
        entity_id: media_player.bedroom
      - service: homeassistant.turn_off
        entity_id: light.master_bedroom

  # romance:
    # alias: Romance Mode
    # sequence:
      # - service: hue.hue_activate_scene
        # data:
          # group_name: "Master Bedroom"
          # scene_name: "Spring blossom"
      # - service: media_player.volume_set
        # data:
          # entity_id: media_player.bedroom
          # volume_level: '0.20'
      # - service: media_player.play_media
        # data:
          # entity_id: media_player.bedroom
          # media_content_id: !secret romance_track1
          # media_content_type: 'audio/mp4'
      # - delay: '00:03:39'
      # - service: media_player.play_media
        # data:
          # entity_id: media_player.bedroom
          # media_content_id: !secret romance_track2
          # media_content_type: 'audio/mp4'
      # - delay: '00:04:29'
      # - service: media_player.play_media
        # data:
          # entity_id: media_player.bedroom
          # media_content_id: !secret romance_track3
          # media_content_type: 'audio/mp4'
      # - delay: '00:03:17'
      # - service: media_player.play_media
        # data:
          # entity_id: media_player.bedroom
          # media_content_id: !secret romance_track4
          # media_content_type: 'audio/mp4'
      # - delay: '00:02:58'
      # - service: media_player.play_media
        # data:
          # entity_id: media_player.bedroom
          # media_content_id: !secret romance_track5
          # media_content_type: 'audio/mp4'