automation:
  - alias: Link New device connected
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.link_alert_mode
      - service: script.link_speech_engine
        data:
          call_greeting: 1
          call_new_device: 1
        data_template:
          person: >-
            {{ trigger.event.data.name }}

  - alias: Link Shut Down
    trigger:
      - event: shutdown
        platform: homeassistant
      - event_type: homeassistant.restart
        platform: event
    action:
      - service: script.link_speech_engine
        data:
          call_bye: 1
          call_shut_down: 1

  - alias: Link Start Up
    trigger:
      - event: start
        platform: homeassistant
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.link_alert_mode
      - service: script.link_speech_engine
        data:
          call_greeting: 1
          call_introduction: 1

  - alias: Link Update Available
    trigger:
      - platform: state
        entity_id: sensor.up_to_date
        from: 'true'
        to: 'false'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.link_alert_mode
      - service: script.link_speech_engine
        data:
          call_greeting: 1
          call_update: 1