automation:
  - alias: Link Shut Down
    initial_state: 'on'
    trigger:
      - event: shutdown
        platform: homeassistant
      - event_type: homeassistant.restart
        platform: event
    condition:
      condition: state
      entity_id: input_boolean.maintenance_mode
      state: 'off'
    action:
      - service: script.link_speech_engine
        data:
          call_bye: 1
          call_shut_down: 1

  - alias: Link Start Up
    initial_state: 'on'
    trigger:
      - event: start
        platform: homeassistant
    condition:
      condition: state
      entity_id: input_boolean.maintenance_mode
      state: 'off'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.link_alert_mode
      - service: script.link_speech_engine
        data:
          call_greeting: 1
          call_introduction: 1
