############################################################
#                                                          #
# This package contains the automations that intelligently #
# control lighting based on weather/occupancy/time etc     #
#                                                          #
# DEPENDS ON: Occupancy and Environment                    #
#                                                          #
############################################################


automation:
  - alias: Lights off when daylight
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.dark_outside
      to: 'false'
    condition:
      condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
    action:
      service: homeassistant.turn_off
      entity_id: group.all_lights

  - alias: Lights on when dark - already home
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.dark_outside
      to: 'true'
    condition:
      condition: state
      entity_id: sensor.home_status
      state: 'Occupied'
    action:
      - service: scene.turn_on
        entity_id: scene.livingroom_sunset
      - service: script.landing_light_scene

  - alias: Lights on when dark - arriving home
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.home_status
      to: 'Occupied'
    condition:
      condition: state
      entity_id: sensor.dark_outside
      state: 'true'
    action:
      - service: scene.turn_on
        entity_id: scene.livingroom_bright
      - service: script.landing_light_scene

  - alias: Landing light night mode
    initial_state: 'on'
    trigger:
      - platform: time
        at: '21:31:00'
      - platform: time
        at: '07:31:00'
    condition:
      condition: state
      entity_id: light.landing
      state: 'on'
    action:
      service: script.landing_light_scene

  - alias: Bedtime lights
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.living_room_switch
      to: '4_hold'
    action:
      service: script.set_hue_scene
      data_template:
        group: "Bedroom"
        scene: "Relax"

  - alias: Media player playing
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: media_player.kodi
      to: 'playing'
    condition:
      - condition: state
        entity_id: sensor.dark_outside
        state: 'true'
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ states.media_player.kodi.attributes.media_content_type == "tvshow" }}'
        - condition: template
          value_template: '{{ states.media_player.kodi.attributes.media_content_type == "movie" }}'
    action:
      service: scene.turn_on
      entity_id: scene.livingroom_movie

  - alias: Media player stopped
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: media_player.kodi
      to: 'idle'
    condition:    
      condition: state
      entity_id: sensor.dark_outside
      state: 'true'
    action:
      service: scene.turn_on
      entity_id: scene.livingroom_bright

  - alias: Media player paused
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: media_player.kodi
      to: 'paused'
    condition:
      - condition: state
        entity_id: sensor.dark_outside
        state: 'true'
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ states.media_player.kodi.attributes.media_content_type == "tvshow" }}'
        - condition: template
          value_template: '{{ states.media_player.kodi.attributes.media_content_type == "movie" }}'
    action:
      service: scene.turn_on
      entity_id: scene.livingroom_bright