####################################################
#                                                  #
# This package is where I place things that I'm    #
# testing - like if I add a new platform I may     #
# add notification automations here to ensure      #
# they are working as expected.  I also add things #
# that are short term - like Xmas lights or one    #
# off automations, or anything else seasonal       #
#                                                  #
####################################################

#Alarm testing

automation:
  alias: TEST alarm
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: alarm_control_panel.alarm
  action:
    service: notify.mf
    data_template:
      message: "ALARM TEST - '{{states.alarm_control_panel.alarm.state}}'"