####################################################
#                                                  #
# This package is where I place things that I'm    #
# testing - like if I add a new platform I may     #
# add notification automations here to ensure      #
# they are working as expected.  I also add things #
# that are short term - like Xmas lights or one    #
# off automations, or anything else seasonal       #
#                                                  #
####################################################


automation:
  - alias: xmas lights off
    trigger:
      platform: state
      entity_id: light.living_room
      to: 'off'
    action:
      service: homeassistant.turn_off
      entity_id: switch.xmas_lights

  - alias: "Xmas lights"
    trigger:
      platform: state
      entity_id: light.living_room
      to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: switch.xmas_lights