#
#
#
#
#MISC!!!!!!!!!!!!!!!!!!!!!!!!!!
#
#
#

homeassistant:
  customize:
    script.romance:
      can_cancel: false
      icon: mdi:creation

    script.lullaby:
      can_cancel: false
      icon: mdi:creation


group:
  masterbed_modes:
    name: Modes
    control: hidden
    entities:
      - script.lullaby
      - script.romance


automation:
  - alias: 'Doorbell test'
    initial_state: 'on'
    trigger:
      platform: mqtt
      topic: home-assistant/doorbell
      payload: 'Ring'
    action:
      service: notify.telegram_marc
      data:
        message: 'Doorbell test'

  - alias: xmas lights off
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: light.living_room
      to: 'off'
    action:
      service: homeassistant.turn_off
      entity_id: switch.xmas_lights

  - alias: "Xmas lights"
    initial_state: on
    trigger:
      platform: state
      entity_id: light.living_room
      to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: switch.xmas_lights

script:
  lullaby:
    alias: Lullaby Mode
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroomcca
          volume_level: '0.20'
      - service: media_player.play_media
        data:
          entity_id: media_player.bedroomcca
          media_content_id: http://37.59.28.208:8543/stream
          media_content_type: 'audio/mp4'
      - service: light.hue_activate_scene
        data:
          group_name: "Master Bedroom"
          scene_name: "Nightlight"
      - service: light.turn_off
        entity_id: light.bedroom_stairs
      - delay: '00:15:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroomcca
          volume_level: '0.15'
      - delay: '00:15:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroomcca
          volume_level: '0.10'
      - delay: '00:15:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroomcca
          volume_level: '0.05'
      - delay: '00:15:00'
      - service: media_player.turn_off
        entity_id: media_player.bedroomcca
      - service: homeassistant.turn_off
        entity_id: light.master_bedroom

  romance:
    alias: Romance Mode
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Master Bedroom"
          scene_name: "Spring blossom"
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroomcca
          volume_level: '0.20'
      - service: media_player.play_media
        data:
          entity_id: media_player.bedroomcca
          media_content_id: !secret romance_track1
          media_content_type: 'audio/mp4'
      - delay: '00:03:39'
      - service: media_player.play_media
        data:
          entity_id: media_player.bedroomcca
          media_content_id: !secret romance_track2
          media_content_type: 'audio/mp4'
      - delay: '00:04:29'
      - service: media_player.play_media
        data:
          entity_id: media_player.bedroomcca
          media_content_id: !secret romance_track3
          media_content_type: 'audio/mp4'
      - delay: '00:03:17'
      - service: media_player.play_media
        data:
          entity_id: media_player.bedroomcca
          media_content_id: !secret romance_track4
          media_content_type: 'audio/mp4'
      - delay: '00:02:58'
      - service: media_player.play_media
        data:
          entity_id: media_player.bedroomcca
          media_content_id: !secret romance_track5
          media_content_type: 'audio/mp4'