##########################################
#                                        #
# This package contains the sensors and  #
# UI elements for my security monitoring #
#                                        #
##########################################

homeassistant:
  customize_glob:
    "sensor.breaches*":
      icon: mdi:email-secure
      
      
alarm_control_panel:
  - platform: manual_mqtt
    name: "Alarm"
    code: !secret alarm_code
    state_topic: homeassistant/alarm
    command_topic: homeassistant/alarm/set
    

sensor:
  - platform: haveibeenpwned
    email: !secret haveibeenpwned_email

binary_sensor:
  - platform: mqtt
    state_topic: "sensor-zero/motion/motion"
    name: "TEST-Motion"
    payload_on: 1
    payload_off: 0
    device_class: motion


group:
  Email Security: !secret email_security
  
  Alarm:
    - alarm_control_panel.alarm


automation:
  - alias: 'Doorbell test'
    trigger:
      platform: mqtt
      topic: home-assistant/doorbell
      payload: 'Ring'
    action:
      service: notify.telegram_marc
      data:
        message: 'Doorbell test'

  - alias: 'Send notification upon failed login attempt'
    trigger:
      platform: state
      entity_id: persistent_notification.httplogin
    condition:
      condition: template
      value_template: "{{ trigger.to_state.state != off }}"
    action:
      service: notify.telegram_marc
      data_template:
        message: "{{ trigger.to_state.state }}"

  - alias: 'Breach email haveibeenpwned connor'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_connor
      above: 0
    action:
      service: notify.telegram_marc
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on Connor email address'

  - alias: 'Breach email haveibeenpwned hass'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_hass
      above: 0
    action:
      service: notify.telegram_marc
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on your HA email address'

  - alias: 'Breach email haveibeenpwned daniel'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_daniel
      above: 0
    action:
      service: notify.telegram_marc
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on Daniel email address'

  - alias: 'Breach email haveibeenpwned laura'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_laura
      above: 1
    action:
      service: notify.telegram_marc
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on Laura email address'

  - alias: 'Breach email haveibeenpwned violet'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_violet
      above: 0
    action:
      service: notify.telegram_marc
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on Violet email address'
    
  - alias: 'Breach email haveibeenpwned social'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_social
      above: 0
    action:
      service: notify.telegram_marc
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on your social email address'

  - alias: 'Breach email haveibeenpwned run'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_run
      above: 0
    action:
      service: notify.telegram_marc
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on your admin/run email address'
        
  - alias: 'Breach email haveibeenpwned personal'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_personal
      above: 0
    action:
      service: notify.telegram_marc
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on your personal email address'