##############################################
#Switches the landing lights to a night light#
##############################################

alias: 'Landing light night mode'
initial_state: 'on'
trigger:
  platform: time
  at: '21:30:00'
condition:
  condition: state
  entity_id: light.landing
  state: 'on'
action:
  service: scene.turn_on
  entity_id: scene.landing_night