###########################################################
#                                                         #
# This package contains the components and sensors I use  #
# to monitor the Homeassistant software and system itself #
#                                                         #
###########################################################


recorder:
  purge_interval: 3
  purge_keep_days: 10


logbook: !include ../../extras/includes/logging.yaml


history: !include ../../extras/includes/logging.yaml


python_script:


sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

  - platform: scrape
    name: HA upstream
    resource: https://pypi.org/project/homeassistant/#history
    select: 'a[href^="/project/homeassistant/0"]'


automation:
  - alias: Device - Check automations status
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        hours: '/1'
        minutes: 00
        seconds: 00
    action:
      - delay: 00:02:00
      - service: python_script.all_automations_counter
      - service: python_script.on_automations_counter
      - delay: 00:00:30
      - condition: template
        value_template: "{{ states('sensor.automation_on') != states('sensor.automation_all') }}"
      - service: persistent_notification.create
        data:
          notification_id: "Automations_counter"
          title: "Automations alert"
          message: "Some automations are disabled."

  - alias: Device - Update Available Notifications
    initial_state: on
    trigger:
      platform: state
      entity_id: sensor.ha_upstream
    action:
      - delay: '00:30:00'
      - service: script.notify
        data:
          no_say: 1
          tell: mf
          call_upgrade: 1

  - alias: Device - Disk use alarm
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id: sensor.disk_use_percent_
      above: 85
    action:
      service: script.notify
      data:
        tell: mf
        no_say: 1
        call_hdd_space: 1

  - alias: Device - System load alarm
    initial_state: on
    trigger:
      - platform: numeric_state
        entity_id: sensor.processor_use
        above: 85
      - platform: numeric_state
        entity_id: sensor.memory_use_percent
        above: 85
    action:
      service: script.notify
      data:
        tell: mf
        no_say: 1
        call_system_load: 1

  - alias: Device - Power on
    initial_state: on
    trigger:
      platform: homeassistant
      event: start
    action:
      service: script.notify
      data:
        call_power_on: 1
        tell: adults

  - alias: Device - Clear TTS cache
    initial_state: on
    trigger:
      platform: time
      at: '03:00:00'
    action:
      service: tts.clear_cache
