###########################################################
#                                                         #
# This package contains the components and sensors I use  #
# to monitor the Homeassistant software and system itself #
#                                                         #
###########################################################


recorder:
  purge_interval: 3
  purge_keep_days: 10


logbook: !include ../../extras/includes/logging.yaml


history: !include ../../extras/includes/logging.yaml


python_script:


mqtt_eventstream:
  publish_topic: '/node-zero'


sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: HA upstream
    value_template: "{{ value_json.info.version }}"
    scan_interval: 3600


automation:
  - alias: Device - Check automations status
    initial_state: on
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        hours: '/1'
        minutes: 00
        seconds: 00
    action:
      - delay: 00:02:00
      - service: python_script.all_automations_counter
      - service: python_script.on_automations_counter
      - delay: 00:00:30
      - condition: template
        value_template: "{{ states('sensor.automation_on') != states('sensor.automation_all') }}"
      - service: persistent_notification.create
        data:
          notification_id: "Automations_counter"
          title: "Automations alert"
          message: "Some automations are disabled."

#TODO - move this notification
  - alias: Device - Update Available Notifications
    initial_state: on
    trigger:
      platform: state
      entity_id: sensor.ha_upstream
    action:
      - delay: '00:30:00'
      - service: notify.mf
        data:
          message: "Update for Home Assistant is available.  https://home-assistant.io/blog/"

  - alias: Device - Disk use alarm
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id: sensor.disk_use_percent_
      above: 85
    action:
      - service: script.notify
        data:
          call_inform: 1
          call_hdd_space: 1

  - alias: Device - System load alarm
    initial_state: on
    trigger:
      - platform: numeric_state
        entity_id: sensor.processor_use
        above: 85
      - platform: numeric_state
        entity_id: sensor.memory_use_percent
        above: 85
    action:
      service: script.notify
      data:
        call_inform: 1
        call_system_load: 1

  - alias: Device - Power on
    initial_state: on
    trigger:
      platform: homeassistant
      event: start
    action:
      service: script.notify
      data:
        call_greeting: 1
        call_inform: 1
        call_power_on: 1
