###########################################################
#                                                         #
# This package contains the components and sensors I use  #
# to monitor the Homeassistant software and system itself #
#                                                         #
###########################################################


recorder:
  purge_interval: 3
  purge_keep_days: 10


logbook:
  include:
    entities:
      - switch.heater
      - input_boolean.guest_mode
      - input_boolean.away_mode
      - input_boolean.holiday_mode
    domains:
      - alarm_control_panel
      - alert
      - light
      - sensor
      - binary_sensor
      - device_tracker
      - zwave

  exclude:
    entities:
      - sensor.time
      - sensor.date
      - light.lr_left
      - light.lr_right
      - light.mb_ceiling
      - light.mb_stairs
      - light.bathroom_g


history:
  use_include_order: True
  include:
    entities:
      - switch.heater
      - input_boolean.guest_mode
      - input_boolean.away_mode
      - input_boolean.holiday_mode
    domains:
      - alarm_control_panel
      - alert
      - light
      - sensor
      - binary_sensor
      - device_tracker
      - zwave

  exclude:
    entities:
      - sensor.time
      - sensor.date
      - light.lr_left
      - light.lr_right
      - light.mb_ceiling
      - light.mb_stairs
      - light.bathroom_g


python_script:


mqtt_eventstream:
  publish_topic: '/citadel'


sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot

  - platform: rest
    resource: https://pypi.python.org/pypi/homeassistant/json
    name: HA upstream
    value_template: '{{ value_json.info.version }}'
    scan_interval: 3600


automation:
  - alias: Device - Check automations status
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
      - platform: time
        hours: '/1'
        minutes: 00
        seconds: 00
    action:
      - delay: 00:02:00
      - service: python_script.all_automations_counter
      - service: python_script.on_automations_counter
      - delay: 00:00:30
      - condition: template
        value_template: '{{ ((states.sensor.automation_on.state) != (states.sensor.automation_all.state)) }}'
      - service: persistent_notification.create
        data:
          notification_id: "Automations_counter"
          title: "Automations alert"
          message: "Some automations are disabled."

  - alias: Device - Update Available Notifications
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.ha_upstream
    action:
      - delay: '00:30:00'
      - service: notify.mf
        data:
          message: 'Update for Home Assistant is available.  https://home-assistant.io/blog/'

  - alias: Device - Disk use alarm
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: sensor.disk_use_percent_
      above: 85
    action:
      - service: notify.mf
        data_template:
          message: "Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_percent_.state }}%!"
      - service: persistent_notification.create
        data_template:
          title: "Hard Drive Monitor:"
          message: "Your harddrive is running out of Space! /dev/root:{{ states.sensor.disk_use_percent_.state }}%!"
          notification_id: "Critical Alert"

  - alias: Device - System load alarm
    initial_state: on
    trigger:
      - platform: numeric_state
        entity_id: sensor.processor_use
        above: 85
      - platform: numeric_state
        entity_id: sensor.memory_use_percent
        above: 85
    action:
      - service: notify.mf
        data_template:
          message: "Your system is running under heavy load! CPU:  {{states.sensor.processor_use.state}}% Memory:  {{ states.sensor.memory_use_percent.state }}%!"
      - service: persistent_notification.create
        data_template:
          title: "System Load Monitor:"
          message: "Your system is running under heavy load! CPU:  {{states.sensor.processor_use.state}}% Memory:  {{ states.sensor.memory_use_percent.state }}%!"
          notification_id: "Critical Alert"

  - alias: Device - Power on
    initial_state: 'on'
    trigger:
      platform: homeassistant
      event: start
    action:
      service: script.link_engine
      data:
        call_greeting: 1
        call_inform: 1
        call_poweron: 1

  - alias: Device - Shutting Down
    initial_state: 'on'
    trigger:
      - event: shutdown
        platform: homeassistant
      - event_type: homeassistant.restart
        platform: event
    condition:
      condition: state
      entity_id: input_boolean.maintenance_mode
      state: 'off'
    action:
      service: script.link_engine
      data:
        call_bye: 1
        message: the system is being shutdown!
