############################################
#                                          #
# This package contains the components,    #
# sensors and UI elements for the hardware #
# I have connected to my homeassistant     #
#                                          #
############################################


#zwave:
#  usb_path: /dev/ttyAMA0


hue:
  bridges:
    - host: !secret hue_light_host
    
    
media_player:
  - platform: cast

  - platform: kodi
    name: Kodi
    host: !secret media_host
    port: !secret media_port
    enable_websocket: false
    username: !secret media_username
    password: !secret media_password
    turn_off_action:
      service: media_player.kodi_call_method
      data_template:
        entity_id: '{{ entity_id }}'
        method: System.Shutdown


mqtt:
  broker: !secret mqtt_broker
  
  
emulated_hue:
  host_ip: !secret hue_host_ip
  listen_port: !secret hue_listen_port
  exposed_domains:
    - light
    - input_boolean
    - switch
        
    
switch: 
  - platform: tplink
    host: !secret switch_tplink_host

  - platform: broadlink
    host: !secret switch_broadlink_host
    mac: !secret switch_broadlink_mac
    friendly_name: 'IR remote'
    switches: !include_dir_merge_named ../../extras/includes/ir_codes/


sensor:
  - platform: hue_sensor


binary_sensor:
  - platform: ping
    host: !secret hue_light_host
    name: Hue Hub

  - platform: ping
    host: !secret switch_tplink_host
    name: TP Link

  - platform: ping
    host: !secret switch_broadlink_host
    name: Broadlink

  - platform: ping
    host: !secret cctv_host
    name: CCTV


automation:
  alias: "Turn off heater after fifteen minutes"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: switch.tplink_switch
    to: 'on'
  action:
    - delay: 00:15:00
    - service: homeassistant.turn_off
      entity_id: switch.tplink_switch