##########################################
#                                        #
# This package contains the sensors I    #
# use for my security monitoring         #
#                                        #
##########################################
      
      
alarm_control_panel:
  - platform: manual_mqtt
    name: "Alarm"
    code: !secret alarm_code
    state_topic: homeassistant/alarm
    command_topic: homeassistant/alarm/set


sensor:
  - platform: haveibeenpwned
    email: !secret haveibeenpwned_email

  - platform: mqtt
    name: "Doorbell"
    state_topic: "home-assistant/doorbell"

binary_sensor:
  - platform: mqtt
    state_topic: "/sensor-zero/motion/motion"
    name: "TEST-Motion"
    payload_on: 1
    payload_off: 0
    device_class: motion


automation:
  - alias: 'Doorbell test'
    initial_state: 'on'
    trigger:
      platform: mqtt
      topic: home-assistant/doorbell
      payload: 'Ring'
    action:
      service: notify.mf
      data:
        message: 'Doorbell test'

  - alias: 'Send notification upon failed login attempt'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: persistent_notification.httplogin
    condition:
      condition: template
      value_template: "{{ trigger.to_state.state != off }}"
    action:
      service: notify.mf
      data_template:
        message: "{{ trigger.to_state.state }}"

  - alias: 'Breach email haveibeenpwned cf'
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_cf
      above: 0
    action:
      service: notify.mf
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on CF email address'

  - alias: 'Breach email haveibeenpwned hass'
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_hass
      above: 0
    action:
      service: notify.mf
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on your HA email address'

  - alias: 'Breach email haveibeenpwned df'
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_df
      above: 0
    action:
      service: notify.mf
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on DF email address'

  - alias: 'Breach email haveibeenpwned ls'
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_ls
      above: 1
    action:
      service: notify.mf
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on LS email address'

  - alias: 'Breach email haveibeenpwned vf'
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_vf
      above: 0
    action:
      service: notify.mf
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on VF email address'
    
  - alias: 'Breach email haveibeenpwned social'
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_social
      above: 0
    action:
      service: notify.mf
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on your social email address'

  - alias: 'Breach email haveibeenpwned run'
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_run
      above: 0
    action:
      service: notify.mf
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on your admin/run email address'
        
  - alias: 'Breach email haveibeenpwned personal'
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: !secret sensor_email_personal
      above: 0
    action:
      service: notify.mf
      data:
        message: 'Warning - HaveIbeenPwned detected a breach on your personal email address'